/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CredentialType,
} from '../models/index';
import {
    CredentialTypeFromJSON,
    CredentialTypeToJSON,
} from '../models/index';

export interface ListCredentialTypesRequest {
    page?: number;
    perPage?: number;
    skipPagination?: boolean;
}

/**
 * 
 */
export class AccountsApi extends runtime.BaseAPI {

    /**
     * Get details for the current account.
     * Get Account Details
     */
    async getAccountDetailsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/account`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get details for the current account.
     * Get Account Details
     */
    async getAccountDetails(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getAccountDetailsRaw(initOverrides);
        return await response.value();
    }

    /**
     * List credential types associated with the current user\'s account.
     * List Credential Types
     */
    async listCredentialTypesRaw(requestParameters: ListCredentialTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Set<CredentialType>>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['skipPagination'] != null) {
            queryParameters['skip_pagination'] = requestParameters['skipPagination'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/credential_types`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => new Set(jsonValue.map(CredentialTypeFromJSON)));
    }

    /**
     * List credential types associated with the current user\'s account.
     * List Credential Types
     */
    async listCredentialTypes(requestParameters: ListCredentialTypesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Set<CredentialType>> {
        const response = await this.listCredentialTypesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
