/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdmissionRequest,
  GetAdmissionRequest401Response,
  GetAdmissionRequest403Response,
  GetAdmissionRequest404Response,
  GetAdmissionRequest500Response,
} from '../models/index';
import {
    AdmissionRequestFromJSON,
    AdmissionRequestToJSON,
    GetAdmissionRequest401ResponseFromJSON,
    GetAdmissionRequest401ResponseToJSON,
    GetAdmissionRequest403ResponseFromJSON,
    GetAdmissionRequest403ResponseToJSON,
    GetAdmissionRequest404ResponseFromJSON,
    GetAdmissionRequest404ResponseToJSON,
    GetAdmissionRequest500ResponseFromJSON,
    GetAdmissionRequest500ResponseToJSON,
} from '../models/index';

export interface GetAdmissionRequestRequest {
    id: number;
}

/**
 * 
 */
export class AdmissionRequestsApi extends runtime.BaseAPI {

    /**
     * Returns the status of an admission request created via POST /api/3/channels/:id/admit or POST /api/3/channels/:id/admit_person. Use this to track whether the admission was successful, denied, or is still pending a response from the door controller. 
     * Get admission request status
     */
    async getAdmissionRequestRaw(requestParameters: GetAdmissionRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdmissionRequest>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAdmissionRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/admission_requests/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdmissionRequestFromJSON(jsonValue));
    }

    /**
     * Returns the status of an admission request created via POST /api/3/channels/:id/admit or POST /api/3/channels/:id/admit_person. Use this to track whether the admission was successful, denied, or is still pending a response from the door controller. 
     * Get admission request status
     */
    async getAdmissionRequest(requestParameters: GetAdmissionRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdmissionRequest> {
        const response = await this.getAdmissionRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
