/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Authenticate200Response,
  Authenticate401Response,
  AuthenticateRequest,
} from '../models/index';
import {
    Authenticate200ResponseFromJSON,
    Authenticate200ResponseToJSON,
    Authenticate401ResponseFromJSON,
    Authenticate401ResponseToJSON,
    AuthenticateRequestFromJSON,
    AuthenticateRequestToJSON,
} from '../models/index';

export interface AuthenticateOperationRequest {
    authenticateRequest: AuthenticateRequest;
}

/**
 * 
 */
export class AuthenticationApi extends runtime.BaseAPI {

    /**
     * Authenticate against the API
     */
    async authenticateRaw(requestParameters: AuthenticateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Authenticate200Response>> {
        if (requestParameters['authenticateRequest'] == null) {
            throw new runtime.RequiredError(
                'authenticateRequest',
                'Required parameter "authenticateRequest" was null or undefined when calling authenticate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/auth`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthenticateRequestToJSON(requestParameters['authenticateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Authenticate200ResponseFromJSON(jsonValue));
    }

    /**
     * Authenticate against the API
     */
    async authenticate(requestParameters: AuthenticateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Authenticate200Response> {
        const response = await this.authenticateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
