/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Beacon,
} from '../models/index';
import {
    BeaconFromJSON,
    BeaconToJSON,
} from '../models/index';

export interface ListBeaconsRequest {
    page?: number;
    perPage?: number;
    skipPagination?: boolean;
}

/**
 * 
 */
export class BeaconsApi extends runtime.BaseAPI {

    /**
     * List beacons associated with this account.
     * List Beacons
     */
    async listBeaconsRaw(requestParameters: ListBeaconsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Set<Beacon>>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['skipPagination'] != null) {
            queryParameters['skip_pagination'] = requestParameters['skipPagination'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/beacons`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => new Set(jsonValue.map(BeaconFromJSON)));
    }

    /**
     * List beacons associated with this account.
     * List Beacons
     */
    async listBeacons(requestParameters: ListBeaconsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Set<Beacon>> {
        const response = await this.listBeaconsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
