/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdmitChannel202Response,
  AdmitPerson202Response,
  AdmitPerson403Response,
  AdmitPersonRequest,
  AutoUnlockChannel400Response,
  AutoUnlockChannelRequest,
  Channel,
  GetAdmissionRequest401Response,
  GetAdmissionRequest403Response,
  GetAdmissionRequest404Response,
  GetAdmissionRequest500Response,
  LockdownChannelRequest,
  UnlockChannelRequest,
} from '../models/index';
import {
    AdmitChannel202ResponseFromJSON,
    AdmitChannel202ResponseToJSON,
    AdmitPerson202ResponseFromJSON,
    AdmitPerson202ResponseToJSON,
    AdmitPerson403ResponseFromJSON,
    AdmitPerson403ResponseToJSON,
    AdmitPersonRequestFromJSON,
    AdmitPersonRequestToJSON,
    AutoUnlockChannel400ResponseFromJSON,
    AutoUnlockChannel400ResponseToJSON,
    AutoUnlockChannelRequestFromJSON,
    AutoUnlockChannelRequestToJSON,
    ChannelFromJSON,
    ChannelToJSON,
    GetAdmissionRequest401ResponseFromJSON,
    GetAdmissionRequest401ResponseToJSON,
    GetAdmissionRequest403ResponseFromJSON,
    GetAdmissionRequest403ResponseToJSON,
    GetAdmissionRequest404ResponseFromJSON,
    GetAdmissionRequest404ResponseToJSON,
    GetAdmissionRequest500ResponseFromJSON,
    GetAdmissionRequest500ResponseToJSON,
    LockdownChannelRequestFromJSON,
    LockdownChannelRequestToJSON,
    UnlockChannelRequestFromJSON,
    UnlockChannelRequestToJSON,
} from '../models/index';

export interface AdmitChannelRequest {
    id: number;
}

export interface AdmitPersonOperationRequest {
    id: number;
    admitPersonRequest: AdmitPersonRequest;
}

export interface AutoUnlockChannelOperationRequest {
    id: number;
    autoUnlockChannelRequest?: AutoUnlockChannelRequest;
}

export interface GetChannelRequest {
    id: number;
}

export interface ListChannelsRequest {
    siteId?: number;
    perPage?: number;
    page?: number;
    skipPagination?: boolean;
}

export interface LockdownChannelOperationRequest {
    id: number;
    lockdownChannelRequest?: LockdownChannelRequest;
}

export interface NormalChannelRequest {
    id: number;
}

export interface RegenerateEncryptionKeyRequest {
    id: number;
}

export interface RemoveEncryptionKeyRequest {
    id: number;
}

export interface UnlockChannelOperationRequest {
    id: number;
    unlockChannelRequest?: UnlockChannelRequest;
}

export interface UnlockdownChannelRequest {
    id: number;
}

/**
 * 
 */
export class ChannelsApi extends runtime.BaseAPI {

    /**
     * Requests immediate admission through a channel without specifying a person. This creates an admission request that momentarily unlocks the door. Returns an admission_request_id that can be used to track the status via GET /api/3/admission_requests/:id. Only works when the channel is in normal mode (not in unlock mode). 
     * Admit through channel (any person)
     */
    async admitChannelRaw(requestParameters: AdmitChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdmitChannel202Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling admitChannel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/channels/{id}/admit`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdmitChannel202ResponseFromJSON(jsonValue));
    }

    /**
     * Requests immediate admission through a channel without specifying a person. This creates an admission request that momentarily unlocks the door. Returns an admission_request_id that can be used to track the status via GET /api/3/admission_requests/:id. Only works when the channel is in normal mode (not in unlock mode). 
     * Admit through channel (any person)
     */
    async admitChannel(requestParameters: AdmitChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdmitChannel202Response> {
        const response = await this.admitChannelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Requests admission for a specific person through a channel. This checks if the person has valid credentials and access rights before admitting. Returns an admission_request_id for tracking via GET /api/3/admission_requests/:id. 
     * Admit specific person through channel
     */
    async admitPersonRaw(requestParameters: AdmitPersonOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdmitPerson202Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling admitPerson().'
            );
        }

        if (requestParameters['admitPersonRequest'] == null) {
            throw new runtime.RequiredError(
                'admitPersonRequest',
                'Required parameter "admitPersonRequest" was null or undefined when calling admitPerson().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/channels/{id}/admit_person`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AdmitPersonRequestToJSON(requestParameters['admitPersonRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdmitPerson202ResponseFromJSON(jsonValue));
    }

    /**
     * Requests admission for a specific person through a channel. This checks if the person has valid credentials and access rights before admitting. Returns an admission_request_id for tracking via GET /api/3/admission_requests/:id. 
     * Admit specific person through channel
     */
    async admitPerson(requestParameters: AdmitPersonOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdmitPerson202Response> {
        const response = await this.admitPersonRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Configures a shift during which the channel automatically unlocks. Provide a shift_id to enable auto-unlock, or omit it to disable. 
     * Set auto-unlock shift
     */
    async autoUnlockChannelRaw(requestParameters: AutoUnlockChannelOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Channel>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling autoUnlockChannel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/channels/{id}/auto_unlock`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AutoUnlockChannelRequestToJSON(requestParameters['autoUnlockChannelRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChannelFromJSON(jsonValue));
    }

    /**
     * Configures a shift during which the channel automatically unlocks. Provide a shift_id to enable auto-unlock, or omit it to disable. 
     * Set auto-unlock shift
     */
    async autoUnlockChannel(requestParameters: AutoUnlockChannelOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Channel> {
        const response = await this.autoUnlockChannelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns details for a specific channel (door controller)
     * Get channel details
     */
    async getChannelRaw(requestParameters: GetChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Channel>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getChannel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/channels/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChannelFromJSON(jsonValue));
    }

    /**
     * Returns details for a specific channel (door controller)
     * Get channel details
     */
    async getChannel(requestParameters: GetChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Channel> {
        const response = await this.getChannelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a paginated list of channels (door controllers) accessible to the authenticated user
     * List channels (door controllers)
     */
    async listChannelsRaw(requestParameters: ListChannelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Channel>>> {
        const queryParameters: any = {};

        if (requestParameters['siteId'] != null) {
            queryParameters['site_id'] = requestParameters['siteId'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['skipPagination'] != null) {
            queryParameters['skip_pagination'] = requestParameters['skipPagination'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/channels`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ChannelFromJSON));
    }

    /**
     * Returns a paginated list of channels (door controllers) accessible to the authenticated user
     * List channels (door controllers)
     */
    async listChannels(requestParameters: ListChannelsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Channel>> {
        const response = await this.listChannelsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Puts a channel into lockdown mode, restricting various types of access. You can selectively lock down card access, REX (Request to Exit), and AUX inputs. 
     * Enable lockdown mode
     */
    async lockdownChannelRaw(requestParameters: LockdownChannelOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Channel>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling lockdownChannel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/channels/{id}/lockdown`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LockdownChannelRequestToJSON(requestParameters['lockdownChannelRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChannelFromJSON(jsonValue));
    }

    /**
     * Puts a channel into lockdown mode, restricting various types of access. You can selectively lock down card access, REX (Request to Exit), and AUX inputs. 
     * Enable lockdown mode
     */
    async lockdownChannel(requestParameters: LockdownChannelOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Channel> {
        const response = await this.lockdownChannelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Cancels unlock mode and returns the channel to normal access control mode
     * Return channel to normal mode
     */
    async normalChannelRaw(requestParameters: NormalChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Channel>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling normalChannel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/channels/{id}/normal`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChannelFromJSON(jsonValue));
    }

    /**
     * Cancels unlock mode and returns the channel to normal access control mode
     * Return channel to normal mode
     */
    async normalChannel(requestParameters: NormalChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Channel> {
        const response = await this.normalChannelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generates a new encryption key for secure communication with the channel
     * Regenerate encryption key
     */
    async regenerateEncryptionKeyRaw(requestParameters: RegenerateEncryptionKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Channel>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling regenerateEncryptionKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/channels/{id}/regenerate_encryption_key`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChannelFromJSON(jsonValue));
    }

    /**
     * Generates a new encryption key for secure communication with the channel
     * Regenerate encryption key
     */
    async regenerateEncryptionKey(requestParameters: RegenerateEncryptionKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Channel> {
        const response = await this.regenerateEncryptionKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes the encryption key, disabling encrypted communication with the channel
     * Remove encryption key
     */
    async removeEncryptionKeyRaw(requestParameters: RemoveEncryptionKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Channel>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling removeEncryptionKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/channels/{id}/remove_encryption_key`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChannelFromJSON(jsonValue));
    }

    /**
     * Removes the encryption key, disabling encrypted communication with the channel
     * Remove encryption key
     */
    async removeEncryptionKey(requestParameters: RemoveEncryptionKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Channel> {
        const response = await this.removeEncryptionKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Puts a channel into unlock mode, where the door remains unlocked until a specified time. If no relock_at time is provided, the door remains unlocked until normal mode is restored. 
     * Unlock channel (unlock mode)
     */
    async unlockChannelRaw(requestParameters: UnlockChannelOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Channel>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling unlockChannel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/channels/{id}/unlock`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UnlockChannelRequestToJSON(requestParameters['unlockChannelRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChannelFromJSON(jsonValue));
    }

    /**
     * Puts a channel into unlock mode, where the door remains unlocked until a specified time. If no relock_at time is provided, the door remains unlocked until normal mode is restored. 
     * Unlock channel (unlock mode)
     */
    async unlockChannel(requestParameters: UnlockChannelOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Channel> {
        const response = await this.unlockChannelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes lockdown mode from a channel, restoring normal access control
     * Disable lockdown mode
     */
    async unlockdownChannelRaw(requestParameters: UnlockdownChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Channel>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling unlockdownChannel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/channels/{id}/unlockdown`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChannelFromJSON(jsonValue));
    }

    /**
     * Removes lockdown mode from a channel, restoring normal access control
     * Disable lockdown mode
     */
    async unlockdownChannel(requestParameters: UnlockdownChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Channel> {
        const response = await this.unlockdownChannelRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
