/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CredentialType,
  GetAdmissionRequest401Response,
  GetAdmissionRequest403Response,
  GetAdmissionRequest500Response,
} from '../models/index';
import {
    CredentialTypeFromJSON,
    CredentialTypeToJSON,
    GetAdmissionRequest401ResponseFromJSON,
    GetAdmissionRequest401ResponseToJSON,
    GetAdmissionRequest403ResponseFromJSON,
    GetAdmissionRequest403ResponseToJSON,
    GetAdmissionRequest500ResponseFromJSON,
    GetAdmissionRequest500ResponseToJSON,
} from '../models/index';

export interface ListCredentialTypesRequest {
    perPage?: number;
    page?: number;
    skipPagination?: boolean;
}

/**
 * 
 */
export class CredentialTypesApi extends runtime.BaseAPI {

    /**
     * Returns a paginated list of credential types configured for the authenticated user\'s account. Credential types define the formats and types of credentials (cards, PINs, mobile access, etc.) that can be used. Each credential type is based on a global credential type and can be customized per account. 
     * List credential types
     */
    async listCredentialTypesRaw(requestParameters: ListCredentialTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CredentialType>>> {
        const queryParameters: any = {};

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['skipPagination'] != null) {
            queryParameters['skip_pagination'] = requestParameters['skipPagination'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/credential_types`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CredentialTypeFromJSON));
    }

    /**
     * Returns a paginated list of credential types configured for the authenticated user\'s account. Credential types define the formats and types of credentials (cards, PINs, mobile access, etc.) that can be used. Each credential type is based on a global credential type and can be customized per account. 
     * List credential types
     */
    async listCredentialTypes(requestParameters: ListCredentialTypesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CredentialType>> {
        const response = await this.listCredentialTypesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
