/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateCredential422Response,
  Credential,
  CredentialInput,
  CredentialUpdateInput,
  GetAdmissionRequest401Response,
  GetAdmissionRequest403Response,
  GetAdmissionRequest404Response,
  GetAdmissionRequest500Response,
} from '../models/index';
import {
    CreateCredential422ResponseFromJSON,
    CreateCredential422ResponseToJSON,
    CredentialFromJSON,
    CredentialToJSON,
    CredentialInputFromJSON,
    CredentialInputToJSON,
    CredentialUpdateInputFromJSON,
    CredentialUpdateInputToJSON,
    GetAdmissionRequest401ResponseFromJSON,
    GetAdmissionRequest401ResponseToJSON,
    GetAdmissionRequest403ResponseFromJSON,
    GetAdmissionRequest403ResponseToJSON,
    GetAdmissionRequest404ResponseFromJSON,
    GetAdmissionRequest404ResponseToJSON,
    GetAdmissionRequest500ResponseFromJSON,
    GetAdmissionRequest500ResponseToJSON,
} from '../models/index';

export interface CreateCredentialRequest {
    personId: number;
    credentialInput: CredentialInput;
}

export interface DeleteCredentialRequest {
    personId: number;
    id: string;
}

export interface GetCredentialRequest {
    personId: number;
    id: string;
    callback?: string;
    ackToken?: string;
}

export interface ListAllCredentialsRequest {
    perPage?: number;
    page?: number;
    skipPagination?: boolean;
}

export interface ListPersonCredentialsRequest {
    personId: number;
    perPage?: number;
    page?: number;
    skipPagination?: boolean;
}

export interface UpdateCredentialRequest {
    personId: number;
    id: string;
    credentialUpdateInput: CredentialUpdateInput;
}

/**
 * 
 */
export class CredentialsApi extends runtime.BaseAPI {

    /**
     * Creates a new credential for a person. For HID Mobile Access and PassFlow credentials, this initiates an invitation process.
     * Create credential
     */
    async createCredentialRaw(requestParameters: CreateCredentialRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Credential>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling createCredential().'
            );
        }

        if (requestParameters['credentialInput'] == null) {
            throw new runtime.RequiredError(
                'credentialInput',
                'Required parameter "credentialInput" was null or undefined when calling createCredential().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/people/{person_id}/credentials`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CredentialInputToJSON(requestParameters['credentialInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CredentialFromJSON(jsonValue));
    }

    /**
     * Creates a new credential for a person. For HID Mobile Access and PassFlow credentials, this initiates an invitation process.
     * Create credential
     */
    async createCredential(requestParameters: CreateCredentialRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Credential> {
        const response = await this.createCredentialRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a credential. For HID Mobile Access credentials, this deactivates the mobile credential.
     * Delete credential
     */
    async deleteCredentialRaw(requestParameters: DeleteCredentialRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling deleteCredential().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteCredential().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/people/{person_id}/credentials/{id}`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Deletes a credential. For HID Mobile Access credentials, this deactivates the mobile credential.
     * Delete credential
     */
    async deleteCredential(requestParameters: DeleteCredentialRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.deleteCredentialRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns details for a specific credential
     * Get credential details
     */
    async getCredentialRaw(requestParameters: GetCredentialRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Credential>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling getCredential().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCredential().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['callback'] != null) {
            queryParameters['callback'] = requestParameters['callback'];
        }

        if (requestParameters['ackToken'] != null) {
            queryParameters['ack_token'] = requestParameters['ackToken'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/people/{person_id}/credentials/{id}`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CredentialFromJSON(jsonValue));
    }

    /**
     * Returns details for a specific credential
     * Get credential details
     */
    async getCredential(requestParameters: GetCredentialRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Credential> {
        const response = await this.getCredentialRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a paginated list of all credentials accessible to the authenticated user
     * List all credentials
     */
    async listAllCredentialsRaw(requestParameters: ListAllCredentialsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Credential>>> {
        const queryParameters: any = {};

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['skipPagination'] != null) {
            queryParameters['skip_pagination'] = requestParameters['skipPagination'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/credentials`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CredentialFromJSON));
    }

    /**
     * Returns a paginated list of all credentials accessible to the authenticated user
     * List all credentials
     */
    async listAllCredentials(requestParameters: ListAllCredentialsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Credential>> {
        const response = await this.listAllCredentialsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a paginated list of credentials for a specific person, or all credentials if no person_id is provided
     * List person credentials
     */
    async listPersonCredentialsRaw(requestParameters: ListPersonCredentialsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Credential>>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling listPersonCredentials().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['skipPagination'] != null) {
            queryParameters['skip_pagination'] = requestParameters['skipPagination'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/people/{person_id}/credentials`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CredentialFromJSON));
    }

    /**
     * Returns a paginated list of credentials for a specific person, or all credentials if no person_id is provided
     * List person credentials
     */
    async listPersonCredentials(requestParameters: ListPersonCredentialsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Credential>> {
        const response = await this.listPersonCredentialsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates the value of an existing credential
     * Update credential
     */
    async updateCredentialRaw(requestParameters: UpdateCredentialRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Credential>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling updateCredential().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateCredential().'
            );
        }

        if (requestParameters['credentialUpdateInput'] == null) {
            throw new runtime.RequiredError(
                'credentialUpdateInput',
                'Required parameter "credentialUpdateInput" was null or undefined when calling updateCredential().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/people/{person_id}/credentials/{id}`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CredentialUpdateInputToJSON(requestParameters['credentialUpdateInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CredentialFromJSON(jsonValue));
    }

    /**
     * Updates the value of an existing credential
     * Update credential
     */
    async updateCredential(requestParameters: UpdateCredentialRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Credential> {
        const response = await this.updateCredentialRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
