/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CredentialType,
} from '../models/index';
import {
    CredentialTypeFromJSON,
    CredentialTypeToJSON,
} from '../models/index';

export interface DeleteCredentialsForPersonByIDRequest {
    personId: number;
}

export interface ListCredentialTypesRequest {
    page?: number;
    perPage?: number;
    skipPagination?: boolean;
}

export interface UpdateCredentialsForPersonByIDRequest {
    personId: number;
}

export interface UpdateCredentialsForPersonByIDPATCHRequest {
    personId: number;
}

/**
 * 
 */
export class CredentialsApi extends runtime.BaseAPI {

    /**
     * Create credentials
     */
    async createCredentialsForPersonRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/people/credentials`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Create credentials
     */
    async createCredentialsForPerson(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.createCredentialsForPersonRaw(initOverrides);
        return await response.value();
    }

    /**
     * Delete credentials
     * Delete Credentials
     */
    async deleteCredentialsForPersonByIDRaw(requestParameters: DeleteCredentialsForPersonByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling deleteCredentialsForPersonByID().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/people/{personId}/credentials`;
        urlPath = urlPath.replace(`{${"personId"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete credentials
     * Delete Credentials
     */
    async deleteCredentialsForPersonByID(requestParameters: DeleteCredentialsForPersonByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteCredentialsForPersonByIDRaw(requestParameters, initOverrides);
    }

    /**
     * List credential types associated with the current user\'s account.
     * List Credential Types
     */
    async listCredentialTypesRaw(requestParameters: ListCredentialTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Set<CredentialType>>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['skipPagination'] != null) {
            queryParameters['skip_pagination'] = requestParameters['skipPagination'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/credential_types`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => new Set(jsonValue.map(CredentialTypeFromJSON)));
    }

    /**
     * List credential types associated with the current user\'s account.
     * List Credential Types
     */
    async listCredentialTypes(requestParameters: ListCredentialTypesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Set<CredentialType>> {
        const response = await this.listCredentialTypesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get credentials for person
     * Get Person Credentials
     */
    async listCredentialsForPersonRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/people/credentials`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get credentials for person
     * Get Person Credentials
     */
    async listCredentialsForPerson(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.listCredentialsForPersonRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update credentials
     * Update Credentials
     */
    async updateCredentialsForPersonByIDRaw(requestParameters: UpdateCredentialsForPersonByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling updateCredentialsForPersonByID().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/people/{personId}/credentials`;
        urlPath = urlPath.replace(`{${"personId"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Update credentials
     * Update Credentials
     */
    async updateCredentialsForPersonByID(requestParameters: UpdateCredentialsForPersonByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.updateCredentialsForPersonByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update credentials
     * Update Credentials
     */
    async updateCredentialsForPersonByIDPATCHRaw(requestParameters: UpdateCredentialsForPersonByIDPATCHRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling updateCredentialsForPersonByIDPATCH().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/people/{personId}/credentials`;
        urlPath = urlPath.replace(`{${"personId"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Update credentials
     * Update Credentials
     */
    async updateCredentialsForPersonByIDPATCH(requestParameters: UpdateCredentialsForPersonByIDPATCHRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.updateCredentialsForPersonByIDPATCHRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
