/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DoorController,
} from '../models/index';
import {
    DoorControllerFromJSON,
    DoorControllerToJSON,
} from '../models/index';

export interface AdmitDoorControllerRequest {
    id: number;
}

export interface AdmitDoorControllerPUTRequest {
    id: number;
}

export interface AutoUnlockDoorControllerRequest {
    id: number;
}

export interface AutoUnlockDoorControllerPUTRequest {
    id: number;
}

export interface GetDoorControllerByIDRequest {
    id: number;
}

export interface LockdownPUTRequest {
    id: number;
}

export interface NormalDoorControllerRequest {
    id: number;
}

export interface RegenerateEncryptionKeyForDoorControllerRequest {
    id: number;
}

export interface RegenerateEncryptionKeyPUTRequest {
    id: number;
}

export interface RemoveEncryptionKeyForDoorControllerRequest {
    id: number;
}

export interface RemoveEncryptionKeyPUTRequest {
    id: number;
}

export interface SetDoorControllerToLockdownModeRequest {
    id: number;
}

export interface SetDoorControllerToNormalModeRequest {
    id: number;
}

export interface SetDoorControllerToUnlockdownModeRequest {
    id: number;
}

export interface UnlockDoorControllerRequest {
    id: number;
}

export interface UnlockDoorControllerPUTRequest {
    id: number;
}

export interface UnlockdownDoorControllerPUTRequest {
    id: number;
}

/**
 * 
 */
export class DoorControllersApi extends runtime.BaseAPI {

    /**
     * Admit person by Door Controller.
     * Admit Door Controller
     */
    async admitDoorControllerRaw(requestParameters: AdmitDoorControllerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling admitDoorController().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/door_controller/{id}/admit`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Admit person by Door Controller.
     * Admit Door Controller
     */
    async admitDoorController(requestParameters: AdmitDoorControllerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.admitDoorControllerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Admit Door Controller
     * Admit Door Controller
     */
    async admitDoorControllerPUTRaw(requestParameters: AdmitDoorControllerPUTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling admitDoorControllerPUT().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/door_controller/{id}/admit`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Admit Door Controller
     * Admit Door Controller
     */
    async admitDoorControllerPUT(requestParameters: AdmitDoorControllerPUTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.admitDoorControllerPUTRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Auto Unlock Door Controller
     * Auto Unlock Door Controller
     */
    async autoUnlockDoorControllerRaw(requestParameters: AutoUnlockDoorControllerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling autoUnlockDoorController().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/door_controller/{id}/auto_unlock`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Auto Unlock Door Controller
     * Auto Unlock Door Controller
     */
    async autoUnlockDoorController(requestParameters: AutoUnlockDoorControllerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.autoUnlockDoorControllerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Auto Unlock Door Controller
     */
    async autoUnlockDoorControllerPUTRaw(requestParameters: AutoUnlockDoorControllerPUTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling autoUnlockDoorControllerPUT().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/door_controller/{id}/auto_unlock`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Auto Unlock Door Controller
     */
    async autoUnlockDoorControllerPUT(requestParameters: AutoUnlockDoorControllerPUTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.autoUnlockDoorControllerPUTRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Door Controller by ID.
     * Get Door Controller by ID
     */
    async getDoorControllerByIDRaw(requestParameters: GetDoorControllerByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DoorController>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDoorControllerByID().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/door_controller/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DoorControllerFromJSON(jsonValue));
    }

    /**
     * Get Door Controller by ID.
     * Get Door Controller by ID
     */
    async getDoorControllerByID(requestParameters: GetDoorControllerByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DoorController> {
        const response = await this.getDoorControllerByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Door Controllers
     * List Door Controllers
     */
    async listDoorControllersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DoorController>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/door_controllers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DoorControllerFromJSON));
    }

    /**
     * List Door Controllers
     * List Door Controllers
     */
    async listDoorControllers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DoorController>> {
        const response = await this.listDoorControllersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Lockdown Door Controller
     * Lockdown Door Controller
     */
    async lockdownPUTRaw(requestParameters: LockdownPUTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling lockdownPUT().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/door_controller/{id}/lockdown`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Lockdown Door Controller
     * Lockdown Door Controller
     */
    async lockdownPUT(requestParameters: LockdownPUTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.lockdownPUTRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Put Door Controller into Normal Mode
     */
    async normalDoorControllerRaw(requestParameters: NormalDoorControllerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling normalDoorController().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/door_controller/{id}/normal`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Put Door Controller into Normal Mode
     */
    async normalDoorController(requestParameters: NormalDoorControllerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.normalDoorControllerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Regenerate Encryption Key for the Door Controller.
     */
    async regenerateEncryptionKeyForDoorControllerRaw(requestParameters: RegenerateEncryptionKeyForDoorControllerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling regenerateEncryptionKeyForDoorController().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/door_controller/{id}/regenerate_encryption_key`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Regenerate Encryption Key for the Door Controller.
     */
    async regenerateEncryptionKeyForDoorController(requestParameters: RegenerateEncryptionKeyForDoorControllerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.regenerateEncryptionKeyForDoorControllerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Regenerate Encryption Key for the Door Controller.
     * Regenerate Encryption Key
     */
    async regenerateEncryptionKeyPUTRaw(requestParameters: RegenerateEncryptionKeyPUTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling regenerateEncryptionKeyPUT().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/door_controller/{id}/regenerate_encryption_key`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Regenerate Encryption Key for the Door Controller.
     * Regenerate Encryption Key
     */
    async regenerateEncryptionKeyPUT(requestParameters: RegenerateEncryptionKeyPUTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.regenerateEncryptionKeyPUTRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove Encryption Key for Door Controller.
     * Remove Encryption Key
     */
    async removeEncryptionKeyForDoorControllerRaw(requestParameters: RemoveEncryptionKeyForDoorControllerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling removeEncryptionKeyForDoorController().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/door_controller/{id}/remove_encryption_key`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Remove Encryption Key for Door Controller.
     * Remove Encryption Key
     */
    async removeEncryptionKeyForDoorController(requestParameters: RemoveEncryptionKeyForDoorControllerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.removeEncryptionKeyForDoorControllerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove Encryption Key for Door Controller.
     */
    async removeEncryptionKeyPUTRaw(requestParameters: RemoveEncryptionKeyPUTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling removeEncryptionKeyPUT().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/door_controller/{id}/remove_encryption_key`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Remove Encryption Key for Door Controller.
     */
    async removeEncryptionKeyPUT(requestParameters: RemoveEncryptionKeyPUTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.removeEncryptionKeyPUTRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Set door controller to lockdown mode.
     * Lockdown Door Controller
     */
    async setDoorControllerToLockdownModeRaw(requestParameters: SetDoorControllerToLockdownModeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling setDoorControllerToLockdownMode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/door_controller/{id}/lockdown`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Set door controller to lockdown mode.
     * Lockdown Door Controller
     */
    async setDoorControllerToLockdownMode(requestParameters: SetDoorControllerToLockdownModeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.setDoorControllerToLockdownModeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Set door controller to normal mode.
     * Set Door Controller to Normal Mode
     */
    async setDoorControllerToNormalModeRaw(requestParameters: SetDoorControllerToNormalModeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling setDoorControllerToNormalMode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/door_controller/{id}/normal`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Set door controller to normal mode.
     * Set Door Controller to Normal Mode
     */
    async setDoorControllerToNormalMode(requestParameters: SetDoorControllerToNormalModeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.setDoorControllerToNormalModeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Take Door Controller out of lockdown mode.
     * Unlockdown Door Controller
     */
    async setDoorControllerToUnlockdownModeRaw(requestParameters: SetDoorControllerToUnlockdownModeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling setDoorControllerToUnlockdownMode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/door_controller/{id}/unlockdown`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Take Door Controller out of lockdown mode.
     * Unlockdown Door Controller
     */
    async setDoorControllerToUnlockdownMode(requestParameters: SetDoorControllerToUnlockdownModeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.setDoorControllerToUnlockdownModeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unlock Door Controller.
     * Unlock Door Controller
     */
    async unlockDoorControllerRaw(requestParameters: UnlockDoorControllerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling unlockDoorController().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/door_controller/{id}/unlock`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Unlock Door Controller.
     * Unlock Door Controller
     */
    async unlockDoorController(requestParameters: UnlockDoorControllerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.unlockDoorControllerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unlock Door Controller.
     * Unlock Door Controller
     */
    async unlockDoorControllerPUTRaw(requestParameters: UnlockDoorControllerPUTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling unlockDoorControllerPUT().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/door_controller/{id}/unlock`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Unlock Door Controller.
     * Unlock Door Controller
     */
    async unlockDoorControllerPUT(requestParameters: UnlockDoorControllerPUTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.unlockDoorControllerPUTRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unlockdown Door Controller
     */
    async unlockdownDoorControllerPUTRaw(requestParameters: UnlockdownDoorControllerPUTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling unlockdownDoorControllerPUT().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/door_controller/{id}/unlockdown`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Unlockdown Door Controller
     */
    async unlockdownDoorControllerPUT(requestParameters: UnlockdownDoorControllerPUTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.unlockdownDoorControllerPUTRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
