/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface RegenerateEncryptionKeyForDoorControllerRequest {
    id: number;
}

export interface RegenerateEncryptionKeyPUTRequest {
    id: number;
}

export interface RemoveEncryptionKeyForDoorControllerRequest {
    id: number;
}

export interface RemoveEncryptionKeyPUTRequest {
    id: number;
}

/**
 * 
 */
export class EncryptionKeysApi extends runtime.BaseAPI {

    /**
     * Regenerate Encryption Key for the Door Controller.
     */
    async regenerateEncryptionKeyForDoorControllerRaw(requestParameters: RegenerateEncryptionKeyForDoorControllerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling regenerateEncryptionKeyForDoorController().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/door_controller/{id}/regenerate_encryption_key`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Regenerate Encryption Key for the Door Controller.
     */
    async regenerateEncryptionKeyForDoorController(requestParameters: RegenerateEncryptionKeyForDoorControllerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.regenerateEncryptionKeyForDoorControllerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Regenerate Encryption Key for the Door Controller.
     * Regenerate Encryption Key
     */
    async regenerateEncryptionKeyPUTRaw(requestParameters: RegenerateEncryptionKeyPUTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling regenerateEncryptionKeyPUT().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/door_controller/{id}/regenerate_encryption_key`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Regenerate Encryption Key for the Door Controller.
     * Regenerate Encryption Key
     */
    async regenerateEncryptionKeyPUT(requestParameters: RegenerateEncryptionKeyPUTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.regenerateEncryptionKeyPUTRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove Encryption Key for Door Controller.
     * Remove Encryption Key
     */
    async removeEncryptionKeyForDoorControllerRaw(requestParameters: RemoveEncryptionKeyForDoorControllerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling removeEncryptionKeyForDoorController().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/door_controller/{id}/remove_encryption_key`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Remove Encryption Key for Door Controller.
     * Remove Encryption Key
     */
    async removeEncryptionKeyForDoorController(requestParameters: RemoveEncryptionKeyForDoorControllerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.removeEncryptionKeyForDoorControllerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove Encryption Key for Door Controller.
     */
    async removeEncryptionKeyPUTRaw(requestParameters: RemoveEncryptionKeyPUTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling removeEncryptionKeyPUT().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/door_controller/{id}/remove_encryption_key`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Remove Encryption Key for Door Controller.
     */
    async removeEncryptionKeyPUT(requestParameters: RemoveEncryptionKeyPUTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.removeEncryptionKeyPUTRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
