/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Event,
  GetAdmissionRequest401Response,
  GetAdmissionRequest403Response,
  GetAdmissionRequest404Response,
  GetAdmissionRequest500Response,
  ListEvents400Response,
} from '../models/index';
import {
    EventFromJSON,
    EventToJSON,
    GetAdmissionRequest401ResponseFromJSON,
    GetAdmissionRequest401ResponseToJSON,
    GetAdmissionRequest403ResponseFromJSON,
    GetAdmissionRequest403ResponseToJSON,
    GetAdmissionRequest404ResponseFromJSON,
    GetAdmissionRequest404ResponseToJSON,
    GetAdmissionRequest500ResponseFromJSON,
    GetAdmissionRequest500ResponseToJSON,
    ListEvents400ResponseFromJSON,
    ListEvents400ResponseToJSON,
} from '../models/index';

export interface GetEventRequest {
    id: number;
    callback?: string;
    ackToken?: string;
}

export interface ListEventsRequest {
    eventCodes?: Array<number>;
    firstName?: string;
    lastName?: string;
    channels?: Array<number>;
    doorControllers?: Array<number>;
    since?: Date;
    level?: ListEventsLevelEnum;
    sort?: ListEventsSortEnum;
    n?: number;
    page?: number;
}

/**
 * 
 */
export class EventsApi extends runtime.BaseAPI {

    /**
     * Returns details for a specific event by ID. Supports webhook acknowledgment via callback/ack_token parameters.
     * Get event details
     */
    async getEventRaw(requestParameters: GetEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Event>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEvent().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['callback'] != null) {
            queryParameters['callback'] = requestParameters['callback'];
        }

        if (requestParameters['ackToken'] != null) {
            queryParameters['ack_token'] = requestParameters['ackToken'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/events/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventFromJSON(jsonValue));
    }

    /**
     * Returns details for a specific event by ID. Supports webhook acknowledgment via callback/ack_token parameters.
     * Get event details
     */
    async getEvent(requestParameters: GetEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Event> {
        const response = await this.getEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a paginated list of events (access control activity logs) for the authenticated user\'s account. By default, returns person access events (admits and rejects) from the last 90 days. Use `event_codes` parameter to filter by specific event types, or `level=debug` to include channel status events. 
     * List events
     */
    async listEventsRaw(requestParameters: ListEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Event>>> {
        const queryParameters: any = {};

        if (requestParameters['eventCodes'] != null) {
            queryParameters['event_codes'] = requestParameters['eventCodes']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['firstName'] != null) {
            queryParameters['first_name'] = requestParameters['firstName'];
        }

        if (requestParameters['lastName'] != null) {
            queryParameters['last_name'] = requestParameters['lastName'];
        }

        if (requestParameters['channels'] != null) {
            queryParameters['channels'] = requestParameters['channels']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['doorControllers'] != null) {
            queryParameters['door_controllers'] = requestParameters['doorControllers']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['since'] != null) {
            queryParameters['since'] = requestParameters['since'];
        }

        if (requestParameters['level'] != null) {
            queryParameters['level'] = requestParameters['level'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['n'] != null) {
            queryParameters['n'] = requestParameters['n'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/events`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EventFromJSON));
    }

    /**
     * Returns a paginated list of events (access control activity logs) for the authenticated user\'s account. By default, returns person access events (admits and rejects) from the last 90 days. Use `event_codes` parameter to filter by specific event types, or `level=debug` to include channel status events. 
     * List events
     */
    async listEvents(requestParameters: ListEventsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Event>> {
        const response = await this.listEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListEventsLevelEnum = {
    Debug: 'debug'
} as const;
export type ListEventsLevelEnum = typeof ListEventsLevelEnum[keyof typeof ListEventsLevelEnum];
/**
 * @export
 */
export const ListEventsSortEnum = {
    Asc: 'ASC',
    Desc: 'DESC'
} as const;
export type ListEventsSortEnum = typeof ListEventsSortEnum[keyof typeof ListEventsSortEnum];
