/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateCredential422Response,
  DeleteGroupReservation200Response,
  GetAdmissionRequest401Response,
  GetAdmissionRequest403Response,
  GetAdmissionRequest404Response,
  GetAdmissionRequest500Response,
  GroupReservation,
  GroupReservationInput,
} from '../models/index';
import {
    CreateCredential422ResponseFromJSON,
    CreateCredential422ResponseToJSON,
    DeleteGroupReservation200ResponseFromJSON,
    DeleteGroupReservation200ResponseToJSON,
    GetAdmissionRequest401ResponseFromJSON,
    GetAdmissionRequest401ResponseToJSON,
    GetAdmissionRequest403ResponseFromJSON,
    GetAdmissionRequest403ResponseToJSON,
    GetAdmissionRequest404ResponseFromJSON,
    GetAdmissionRequest404ResponseToJSON,
    GetAdmissionRequest500ResponseFromJSON,
    GetAdmissionRequest500ResponseToJSON,
    GroupReservationFromJSON,
    GroupReservationToJSON,
    GroupReservationInputFromJSON,
    GroupReservationInputToJSON,
} from '../models/index';

export interface CreateGroupReservationRequest {
    groupReservationInput: GroupReservationInput;
}

export interface DeleteGroupReservationRequest {
    id: number;
}

export interface ListGroupReservationsRequest {
    since?: Date;
    sinceUtc?: Date;
    perPage?: number;
    page?: number;
    skipPagination?: boolean;
}

/**
 * 
 */
export class GroupReservationsApi extends runtime.BaseAPI {

    /**
     * Creates a new group reservation to temporarily assign a person to one or more groups. The person will be automatically added to the specified groups during the reservation period. 
     * Create group reservation
     */
    async createGroupReservationRaw(requestParameters: CreateGroupReservationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupReservation>> {
        if (requestParameters['groupReservationInput'] == null) {
            throw new runtime.RequiredError(
                'groupReservationInput',
                'Required parameter "groupReservationInput" was null or undefined when calling createGroupReservation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/group_reservations`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GroupReservationInputToJSON(requestParameters['groupReservationInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupReservationFromJSON(jsonValue));
    }

    /**
     * Creates a new group reservation to temporarily assign a person to one or more groups. The person will be automatically added to the specified groups during the reservation period. 
     * Create group reservation
     */
    async createGroupReservation(requestParameters: CreateGroupReservationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupReservation> {
        const response = await this.createGroupReservationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes or deactivates a group reservation. If the reservation is pending (not yet started), it will be permanently deleted. If it\'s already active, it will be deactivated and the person will be removed from the assigned groups. 
     * Delete group reservation
     */
    async deleteGroupReservationRaw(requestParameters: DeleteGroupReservationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteGroupReservation200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteGroupReservation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/group_reservations/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteGroupReservation200ResponseFromJSON(jsonValue));
    }

    /**
     * Deletes or deactivates a group reservation. If the reservation is pending (not yet started), it will be permanently deleted. If it\'s already active, it will be deactivated and the person will be removed from the assigned groups. 
     * Delete group reservation
     */
    async deleteGroupReservation(requestParameters: DeleteGroupReservationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteGroupReservation200Response> {
        const response = await this.deleteGroupReservationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a paginated list of present and future group reservations. Group reservations temporarily assign people to groups for a specified time period. Supports incremental sync via `since` or `since_utc` parameters. 
     * List group reservations
     */
    async listGroupReservationsRaw(requestParameters: ListGroupReservationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GroupReservation>>> {
        const queryParameters: any = {};

        if (requestParameters['since'] != null) {
            queryParameters['since'] = requestParameters['since'];
        }

        if (requestParameters['sinceUtc'] != null) {
            queryParameters['since_utc'] = requestParameters['sinceUtc'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['skipPagination'] != null) {
            queryParameters['skip_pagination'] = requestParameters['skipPagination'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/group_reservations`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GroupReservationFromJSON));
    }

    /**
     * Returns a paginated list of present and future group reservations. Group reservations temporarily assign people to groups for a specified time period. Supports incremental sync via `since` or `since_utc` parameters. 
     * List group reservations
     */
    async listGroupReservations(requestParameters: ListGroupReservationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GroupReservation>> {
        const response = await this.listGroupReservationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
