/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetAdmissionRequest401Response,
  GetAdmissionRequest403Response,
  GetAdmissionRequest500Response,
  Group,
} from '../models/index';
import {
    GetAdmissionRequest401ResponseFromJSON,
    GetAdmissionRequest401ResponseToJSON,
    GetAdmissionRequest403ResponseFromJSON,
    GetAdmissionRequest403ResponseToJSON,
    GetAdmissionRequest500ResponseFromJSON,
    GetAdmissionRequest500ResponseToJSON,
    GroupFromJSON,
    GroupToJSON,
} from '../models/index';

/**
 * 
 */
export class GroupsApi extends runtime.BaseAPI {

    /**
     * Returns a list of all groups accessible to the authenticated user, ordered by name. Groups are collections of people that can be assigned to roles for access control. Groups can be static (manually assigned) or dynamic (based on LDAP/directory queries). This endpoint does not support pagination. 
     * List groups
     */
    async listGroupsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Group>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/groups`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GroupFromJSON));
    }

    /**
     * Returns a list of all groups accessible to the authenticated user, ordered by name. Groups are collections of people that can be assigned to roles for access control. Groups can be static (manually assigned) or dynamic (based on LDAP/directory queries). This endpoint does not support pagination. 
     * List groups
     */
    async listGroups(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Group>> {
        const response = await this.listGroupsRaw(initOverrides);
        return await response.value();
    }

}
