/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ListLDAPEndpoints200Response,
} from '../models/index';
import {
    ListLDAPEndpoints200ResponseFromJSON,
    ListLDAPEndpoints200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class LdapApi extends runtime.BaseAPI {

    /**
     * List LDAP endpoints
     */
    async listLDAPEndpointsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListLDAPEndpoints200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/integrations/ldap`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListLDAPEndpoints200ResponseFromJSON(jsonValue));
    }

    /**
     * List LDAP endpoints
     */
    async listLDAPEndpoints(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListLDAPEndpoints200Response> {
        const response = await this.listLDAPEndpointsRaw(initOverrides);
        return await response.value();
    }

}
