/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateCredential422Response,
  DeleteGroupReservation200Response,
  GetAdmissionRequest401Response,
  GetAdmissionRequest403Response,
  GetAdmissionRequest404Response,
  GetAdmissionRequest500Response,
  NotificationRule,
  NotificationRuleInput,
} from '../models/index';
import {
    CreateCredential422ResponseFromJSON,
    CreateCredential422ResponseToJSON,
    DeleteGroupReservation200ResponseFromJSON,
    DeleteGroupReservation200ResponseToJSON,
    GetAdmissionRequest401ResponseFromJSON,
    GetAdmissionRequest401ResponseToJSON,
    GetAdmissionRequest403ResponseFromJSON,
    GetAdmissionRequest403ResponseToJSON,
    GetAdmissionRequest404ResponseFromJSON,
    GetAdmissionRequest404ResponseToJSON,
    GetAdmissionRequest500ResponseFromJSON,
    GetAdmissionRequest500ResponseToJSON,
    NotificationRuleFromJSON,
    NotificationRuleToJSON,
    NotificationRuleInputFromJSON,
    NotificationRuleInputToJSON,
} from '../models/index';

export interface CreateNotificationRuleRequest {
    notificationRuleInput: NotificationRuleInput;
}

export interface DeleteNotificationRuleRequest {
    id: number;
}

export interface GetNotificationRuleRequest {
    id: number;
}

export interface UpdateNotificationRuleRequest {
    id: number;
    notificationRuleInput: NotificationRuleInput;
}

/**
 * 
 */
export class NotificationRulesApi extends runtime.BaseAPI {

    /**
     * Creates a new notification rule to trigger webhooks or other actions when specific events occur. At least one action and one event must be specified. 
     * Create notification rule
     */
    async createNotificationRuleRaw(requestParameters: CreateNotificationRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotificationRule>> {
        if (requestParameters['notificationRuleInput'] == null) {
            throw new runtime.RequiredError(
                'notificationRuleInput',
                'Required parameter "notificationRuleInput" was null or undefined when calling createNotificationRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/notification_rules`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NotificationRuleInputToJSON(requestParameters['notificationRuleInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotificationRuleFromJSON(jsonValue));
    }

    /**
     * Creates a new notification rule to trigger webhooks or other actions when specific events occur. At least one action and one event must be specified. 
     * Create notification rule
     */
    async createNotificationRule(requestParameters: CreateNotificationRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotificationRule> {
        const response = await this.createNotificationRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a notification rule
     * Delete notification rule
     */
    async deleteNotificationRuleRaw(requestParameters: DeleteNotificationRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteGroupReservation200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteNotificationRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/notification_rules/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteGroupReservation200ResponseFromJSON(jsonValue));
    }

    /**
     * Deletes a notification rule
     * Delete notification rule
     */
    async deleteNotificationRule(requestParameters: DeleteNotificationRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteGroupReservation200Response> {
        const response = await this.deleteNotificationRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns details for a specific notification rule
     * Get notification rule details
     */
    async getNotificationRuleRaw(requestParameters: GetNotificationRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotificationRule>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getNotificationRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/notification_rules/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotificationRuleFromJSON(jsonValue));
    }

    /**
     * Returns details for a specific notification rule
     * Get notification rule details
     */
    async getNotificationRule(requestParameters: GetNotificationRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotificationRule> {
        const response = await this.getNotificationRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of all notification rules for the authenticated user. Notification rules define webhooks or other actions that are triggered when specific events occur. This endpoint does not support pagination. 
     * List notification rules
     */
    async listNotificationRulesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<NotificationRule>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/notification_rules`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(NotificationRuleFromJSON));
    }

    /**
     * Returns a list of all notification rules for the authenticated user. Notification rules define webhooks or other actions that are triggered when specific events occur. This endpoint does not support pagination. 
     * List notification rules
     */
    async listNotificationRules(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<NotificationRule>> {
        const response = await this.listNotificationRulesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Updates an existing notification rule. This replaces all conditions, events, and actions with the new values provided in the request. 
     * Update notification rule
     */
    async updateNotificationRuleRaw(requestParameters: UpdateNotificationRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotificationRule>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateNotificationRule().'
            );
        }

        if (requestParameters['notificationRuleInput'] == null) {
            throw new runtime.RequiredError(
                'notificationRuleInput',
                'Required parameter "notificationRuleInput" was null or undefined when calling updateNotificationRule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/notification_rules/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: NotificationRuleInputToJSON(requestParameters['notificationRuleInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotificationRuleFromJSON(jsonValue));
    }

    /**
     * Updates an existing notification rule. This replaces all conditions, events, and actions with the new values provided in the request. 
     * Update notification rule
     */
    async updateNotificationRule(requestParameters: UpdateNotificationRuleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotificationRule> {
        const response = await this.updateNotificationRuleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
