/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface InvitePersonToPassportRequest {
    personId: number;
}

/**
 * 
 */
export class PassportInvitesApi extends runtime.BaseAPI {

    /**
     * Invite a Person to use Passport
     * Invite Person to Passport
     */
    async invitePersonToPassportRaw(requestParameters: InvitePersonToPassportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling invitePersonToPassport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/people/{personId}/passport_invite`;
        urlPath = urlPath.replace(`{${"personId"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Invite a Person to use Passport
     * Invite Person to Passport
     */
    async invitePersonToPassport(requestParameters: InvitePersonToPassportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.invitePersonToPassportRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
