/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateCredential422Response,
  DeleteGroupReservation200Response,
  GetAdmissionRequest401Response,
  GetAdmissionRequest403Response,
  GetAdmissionRequest404Response,
  GetAdmissionRequest500Response,
  Reservation,
  ReservationInput,
} from '../models/index';
import {
    CreateCredential422ResponseFromJSON,
    CreateCredential422ResponseToJSON,
    DeleteGroupReservation200ResponseFromJSON,
    DeleteGroupReservation200ResponseToJSON,
    GetAdmissionRequest401ResponseFromJSON,
    GetAdmissionRequest401ResponseToJSON,
    GetAdmissionRequest403ResponseFromJSON,
    GetAdmissionRequest403ResponseToJSON,
    GetAdmissionRequest404ResponseFromJSON,
    GetAdmissionRequest404ResponseToJSON,
    GetAdmissionRequest500ResponseFromJSON,
    GetAdmissionRequest500ResponseToJSON,
    ReservationFromJSON,
    ReservationToJSON,
    ReservationInputFromJSON,
    ReservationInputToJSON,
} from '../models/index';

export interface CreateReservationRequest {
    reservationInput: ReservationInput;
}

export interface DeleteReservationRequest {
    id: number;
}

export interface ListReservationsRequest {
    since?: Date;
    sinceUtc?: Date;
    perPage?: number;
    page?: number;
    skipPagination?: boolean;
}

/**
 * 
 */
export class ReservationsApi extends runtime.BaseAPI {

    /**
     * Creates a new reservation to grant temporary access to specific channels for a person. The start and end times must fall on the same day in the account\'s time zone. Automatically creates a role and shift for the reservation period. 
     * Create reservation
     */
    async createReservationRaw(requestParameters: CreateReservationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Reservation>> {
        if (requestParameters['reservationInput'] == null) {
            throw new runtime.RequiredError(
                'reservationInput',
                'Required parameter "reservationInput" was null or undefined when calling createReservation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/reservations`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReservationInputToJSON(requestParameters['reservationInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReservationFromJSON(jsonValue));
    }

    /**
     * Creates a new reservation to grant temporary access to specific channels for a person. The start and end times must fall on the same day in the account\'s time zone. Automatically creates a role and shift for the reservation period. 
     * Create reservation
     */
    async createReservation(requestParameters: CreateReservationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Reservation> {
        const response = await this.createReservationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a reservation, removing the temporary access grant. This will also delete the associated role and shift. 
     * Delete reservation
     */
    async deleteReservationRaw(requestParameters: DeleteReservationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteGroupReservation200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteReservation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/reservations/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteGroupReservation200ResponseFromJSON(jsonValue));
    }

    /**
     * Deletes a reservation, removing the temporary access grant. This will also delete the associated role and shift. 
     * Delete reservation
     */
    async deleteReservation(requestParameters: DeleteReservationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteGroupReservation200Response> {
        const response = await this.deleteReservationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a paginated list of future reservations. Reservations grant temporary access to specific channels (door controllers) for a person within a specified time window. Supports incremental sync via `since` or `since_utc` parameters. 
     * List reservations
     */
    async listReservationsRaw(requestParameters: ListReservationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Reservation>>> {
        const queryParameters: any = {};

        if (requestParameters['since'] != null) {
            queryParameters['since'] = requestParameters['since'];
        }

        if (requestParameters['sinceUtc'] != null) {
            queryParameters['since_utc'] = requestParameters['sinceUtc'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['skipPagination'] != null) {
            queryParameters['skip_pagination'] = requestParameters['skipPagination'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/reservations`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ReservationFromJSON));
    }

    /**
     * Returns a paginated list of future reservations. Reservations grant temporary access to specific channels (door controllers) for a person within a specified time window. Supports incremental sync via `since` or `since_utc` parameters. 
     * List reservations
     */
    async listReservations(requestParameters: ListReservationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Reservation>> {
        const response = await this.listReservationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
