/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetAdmissionRequest401Response,
  GetAdmissionRequest403Response,
  GetAdmissionRequest500Response,
  Role,
} from '../models/index';
import {
    GetAdmissionRequest401ResponseFromJSON,
    GetAdmissionRequest401ResponseToJSON,
    GetAdmissionRequest403ResponseFromJSON,
    GetAdmissionRequest403ResponseToJSON,
    GetAdmissionRequest500ResponseFromJSON,
    GetAdmissionRequest500ResponseToJSON,
    RoleFromJSON,
    RoleToJSON,
} from '../models/index';

/**
 * 
 */
export class RolesApi extends runtime.BaseAPI {

    /**
     * Returns a list of all roles accessible to the authenticated user, ordered by name. Roles define which channels (door controllers) people or groups have access to, optionally within specific time shifts. This endpoint does not support pagination. 
     * List roles
     */
    async listRolesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Role>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/roles`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RoleFromJSON));
    }

    /**
     * Returns a list of all roles accessible to the authenticated user, ordered by name. Roles define which channels (door controllers) people or groups have access to, optionally within specific time shifts. This endpoint does not support pagination. 
     * List roles
     */
    async listRoles(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Role>> {
        const response = await this.listRolesRaw(initOverrides);
        return await response.value();
    }

}
