/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Shift,
} from '../models/index';
import {
    ShiftFromJSON,
    ShiftToJSON,
} from '../models/index';

/**
 * 
 */
export class ShiftsApi extends runtime.BaseAPI {

    /**
     * List Shifts
     * List Shifts
     */
    async listShiftsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Set<Shift>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/shifts`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => new Set(jsonValue.map(ShiftFromJSON)));
    }

    /**
     * List Shifts
     * List Shifts
     */
    async listShifts(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Set<Shift>> {
        const response = await this.listShiftsRaw(initOverrides);
        return await response.value();
    }

}
