/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetAdmissionRequest401Response,
  GetAdmissionRequest403Response,
  GetAdmissionRequest500Response,
  Site,
} from '../models/index';
import {
    GetAdmissionRequest401ResponseFromJSON,
    GetAdmissionRequest401ResponseToJSON,
    GetAdmissionRequest403ResponseFromJSON,
    GetAdmissionRequest403ResponseToJSON,
    GetAdmissionRequest500ResponseFromJSON,
    GetAdmissionRequest500ResponseToJSON,
    SiteFromJSON,
    SiteToJSON,
} from '../models/index';

export interface ListSitesRequest {
    perPage?: number;
    page?: number;
    skipPagination?: boolean;
}

/**
 * 
 */
export class SitesApi extends runtime.BaseAPI {

    /**
     * Returns a paginated list of sites (physical locations) accessible to the authenticated user. Sites are used to organize channels (door controllers) by physical location and can have their own time zones and IP address ranges. 
     * List sites
     */
    async listSitesRaw(requestParameters: ListSitesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Site>>> {
        const queryParameters: any = {};

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['skipPagination'] != null) {
            queryParameters['skip_pagination'] = requestParameters['skipPagination'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/sites`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SiteFromJSON));
    }

    /**
     * Returns a paginated list of sites (physical locations) accessible to the authenticated user. Sites are used to organize channels (door controllers) by physical location and can have their own time zones and IP address ranges. 
     * List sites
     */
    async listSites(requestParameters: ListSitesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Site>> {
        const response = await this.listSitesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
