/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TriggerSync200Response,
} from '../models/index';
import {
    TriggerSync200ResponseFromJSON,
    TriggerSync200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class SyncApi extends runtime.BaseAPI {

    /**
     * Trigger Sync of Account
     * Trigger Sync
     */
    async triggerSyncRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TriggerSync200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/sync`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TriggerSync200ResponseFromJSON(jsonValue));
    }

    /**
     * Trigger Sync of Account
     * Trigger Sync
     */
    async triggerSync(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TriggerSync200Response> {
        const response = await this.triggerSyncRaw(initOverrides);
        return await response.value();
    }

}
