/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeleteGroupReservation200Response,
  GetAdmissionRequest401Response,
  GetAdmissionRequest403Response,
  GetAdmissionRequest500Response,
  InitiateSync429Response,
} from '../models/index';
import {
    DeleteGroupReservation200ResponseFromJSON,
    DeleteGroupReservation200ResponseToJSON,
    GetAdmissionRequest401ResponseFromJSON,
    GetAdmissionRequest401ResponseToJSON,
    GetAdmissionRequest403ResponseFromJSON,
    GetAdmissionRequest403ResponseToJSON,
    GetAdmissionRequest500ResponseFromJSON,
    GetAdmissionRequest500ResponseToJSON,
    InitiateSync429ResponseFromJSON,
    InitiateSync429ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class SyncApi extends runtime.BaseAPI {

    /**
     * Triggers a synchronization process to push pending changes to all door controllers. This endpoint initiates the sync if there are unsynced changes in the account. The sync process is rate-limited to prevent excessive sync requests. 
     * Initiate sync
     */
    async initiateSyncRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteGroupReservation200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", []);
        }


        let urlPath = `/api/3/sync`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteGroupReservation200ResponseFromJSON(jsonValue));
    }

    /**
     * Triggers a synchronization process to push pending changes to all door controllers. This endpoint initiates the sync if there are unsynced changes in the account. The sync process is rate-limited to prevent excessive sync requests. 
     * Initiate sync
     */
    async initiateSync(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteGroupReservation200Response> {
        const response = await this.initiateSyncRaw(initOverrides);
        return await response.value();
    }

}
