/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountSync } from './AccountSync';
import {
    AccountSyncFromJSON,
    AccountSyncFromJSONTyped,
    AccountSyncToJSON,
    AccountSyncToJSONTyped,
} from './AccountSync';
import type { AccountUser } from './AccountUser';
import {
    AccountUserFromJSON,
    AccountUserFromJSONTyped,
    AccountUserToJSON,
    AccountUserToJSONTyped,
} from './AccountUser';
import type { AccountReseller } from './AccountReseller';
import {
    AccountResellerFromJSON,
    AccountResellerFromJSONTyped,
    AccountResellerToJSON,
    AccountResellerToJSONTyped,
} from './AccountReseller';
import type { AccountPassport } from './AccountPassport';
import {
    AccountPassportFromJSON,
    AccountPassportFromJSONTyped,
    AccountPassportToJSON,
    AccountPassportToJSONTyped,
} from './AccountPassport';

/**
 * 
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * Unique hashid identifier for the account
     * @type {string}
     * @memberof Account
     */
    id: string;
    /**
     * Name of the account
     * @type {string}
     * @memberof Account
     */
    name: string;
    /**
     * Account's time zone (IANA time zone database format)
     * @type {string}
     * @memberof Account
     */
    timeZone: string;
    /**
     * Whether the account is being monitored
     * @type {boolean}
     * @memberof Account
     */
    monitored: boolean;
    /**
     * 
     * @type {AccountReseller}
     * @memberof Account
     */
    reseller?: AccountReseller | null;
    /**
     * 
     * @type {AccountSync}
     * @memberof Account
     */
    sync: AccountSync;
    /**
     * 
     * @type {AccountUser}
     * @memberof Account
     */
    user: AccountUser;
    /**
     * 
     * @type {AccountPassport}
     * @memberof Account
     */
    passport: AccountPassport;
}

/**
 * Check if a given object implements the Account interface.
 */
export function instanceOfAccount(value: object): value is Account {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('timeZone' in value) || value['timeZone'] === undefined) return false;
    if (!('monitored' in value) || value['monitored'] === undefined) return false;
    if (!('sync' in value) || value['sync'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('passport' in value) || value['passport'] === undefined) return false;
    return true;
}

export function AccountFromJSON(json: any): Account {
    return AccountFromJSONTyped(json, false);
}

export function AccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): Account {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'timeZone': json['time_zone'],
        'monitored': json['monitored'],
        'reseller': json['reseller'] == null ? undefined : AccountResellerFromJSON(json['reseller']),
        'sync': AccountSyncFromJSON(json['sync']),
        'user': AccountUserFromJSON(json['user']),
        'passport': AccountPassportFromJSON(json['passport']),
    };
}

export function AccountToJSON(json: any): Account {
    return AccountToJSONTyped(json, false);
}

export function AccountToJSONTyped(value?: Account | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'time_zone': value['timeZone'],
        'monitored': value['monitored'],
        'reseller': AccountResellerToJSON(value['reseller']),
        'sync': AccountSyncToJSON(value['sync']),
        'user': AccountUserToJSON(value['user']),
        'passport': AccountPassportToJSON(value['passport']),
    };
}

