/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Mobile access features configuration
 * @export
 * @interface AccountPassport
 */
export interface AccountPassport {
    /**
     * Whether passport remote unlock is enabled
     * @type {boolean}
     * @memberof AccountPassport
     */
    remoteUnlockEnabled: boolean;
    /**
     * Whether HID mobile access is configured
     * @type {boolean}
     * @memberof AccountPassport
     */
    hidMobileAccess: boolean;
}

/**
 * Check if a given object implements the AccountPassport interface.
 */
export function instanceOfAccountPassport(value: object): value is AccountPassport {
    if (!('remoteUnlockEnabled' in value) || value['remoteUnlockEnabled'] === undefined) return false;
    if (!('hidMobileAccess' in value) || value['hidMobileAccess'] === undefined) return false;
    return true;
}

export function AccountPassportFromJSON(json: any): AccountPassport {
    return AccountPassportFromJSONTyped(json, false);
}

export function AccountPassportFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountPassport {
    if (json == null) {
        return json;
    }
    return {
        
        'remoteUnlockEnabled': json['remote_unlock_enabled'],
        'hidMobileAccess': json['hid_mobile_access'],
    };
}

export function AccountPassportToJSON(json: any): AccountPassport {
    return AccountPassportToJSONTyped(json, false);
}

export function AccountPassportToJSONTyped(value?: AccountPassport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'remote_unlock_enabled': value['remoteUnlockEnabled'],
        'hid_mobile_access': value['hidMobileAccess'],
    };
}

