/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Synchronization status information
 * @export
 * @interface AccountSync
 */
export interface AccountSync {
    /**
     * Current sync status
     * @type {string}
     * @memberof AccountSync
     */
    status: AccountSyncStatusEnum;
    /**
     * Timestamp of last sync initiation
     * @type {Date}
     * @memberof AccountSync
     */
    lastSync: Date | null;
    /**
     * Detailed description of sync status (e.g., "2 of 5 failed")
     * @type {string}
     * @memberof AccountSync
     */
    description?: string | null;
}


/**
 * @export
 */
export const AccountSyncStatusEnum = {
    Complete: 'complete',
    Failing: 'failing',
    Syncing: 'syncing',
    Pending: 'pending'
} as const;
export type AccountSyncStatusEnum = typeof AccountSyncStatusEnum[keyof typeof AccountSyncStatusEnum];


/**
 * Check if a given object implements the AccountSync interface.
 */
export function instanceOfAccountSync(value: object): value is AccountSync {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('lastSync' in value) || value['lastSync'] === undefined) return false;
    return true;
}

export function AccountSyncFromJSON(json: any): AccountSync {
    return AccountSyncFromJSONTyped(json, false);
}

export function AccountSyncFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountSync {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'lastSync': (json['last_sync'] == null ? null : new Date(json['last_sync'])),
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function AccountSyncToJSON(json: any): AccountSync {
    return AccountSyncToJSONTyped(json, false);
}

export function AccountSyncToJSONTyped(value?: AccountSync | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'last_sync': value['lastSync'] == null ? value['lastSync'] : value['lastSync'].toISOString(),
        'description': value['description'],
    };
}

