/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Reseller information if account has an associated reseller
 * @export
 * @interface AccountReseller
 */
export interface AccountReseller {
    /**
     * Reseller ID
     * @type {number}
     * @memberof AccountReseller
     */
    id?: number;
    /**
     * Reseller name
     * @type {string}
     * @memberof AccountReseller
     */
    name?: string;
    /**
     * Support contact name
     * @type {string}
     * @memberof AccountReseller
     */
    supportContact?: string | null;
    /**
     * Support email address
     * @type {string}
     * @memberof AccountReseller
     */
    supportEmail?: string | null;
    /**
     * Support telephone number
     * @type {string}
     * @memberof AccountReseller
     */
    supportTelephone?: string | null;
}

/**
 * Check if a given object implements the AccountReseller interface.
 */
export function instanceOfAccountReseller(value: object): value is AccountReseller {
    return true;
}

export function AccountResellerFromJSON(json: any): AccountReseller {
    return AccountResellerFromJSONTyped(json, false);
}

export function AccountResellerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountReseller {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'supportContact': json['support_contact'] == null ? undefined : json['support_contact'],
        'supportEmail': json['support_email'] == null ? undefined : json['support_email'],
        'supportTelephone': json['support_telephone'] == null ? undefined : json['support_telephone'],
    };
}

export function AccountResellerToJSON(json: any): AccountReseller {
    return AccountResellerToJSONTyped(json, false);
}

export function AccountResellerToJSONTyped(value?: AccountReseller | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'support_contact': value['supportContact'],
        'support_email': value['supportEmail'],
        'support_telephone': value['supportTelephone'],
    };
}

