/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Current authenticated user information
 * @export
 * @interface AccountUser
 */
export interface AccountUser {
    /**
     * User ID
     * @type {number}
     * @memberof AccountUser
     */
    id: number;
    /**
     * User's first name
     * @type {string}
     * @memberof AccountUser
     */
    firstName: string;
    /**
     * User's last name
     * @type {string}
     * @memberof AccountUser
     */
    lastName: string;
    /**
     * User's email address
     * @type {string}
     * @memberof AccountUser
     */
    email: string;
}

/**
 * Check if a given object implements the AccountUser interface.
 */
export function instanceOfAccountUser(value: object): value is AccountUser {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function AccountUserFromJSON(json: any): AccountUser {
    return AccountUserFromJSONTyped(json, false);
}

export function AccountUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'email': json['email'],
    };
}

export function AccountUserToJSON(json: any): AccountUser {
    return AccountUserToJSONTyped(json, false);
}

export function AccountUserToJSONTyped(value?: AccountUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'email': value['email'],
    };
}

