/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdmissionRequestDoorController } from './AdmissionRequestDoorController';
import {
    AdmissionRequestDoorControllerFromJSON,
    AdmissionRequestDoorControllerFromJSONTyped,
    AdmissionRequestDoorControllerToJSON,
    AdmissionRequestDoorControllerToJSONTyped,
} from './AdmissionRequestDoorController';
import type { AdmissionRequestPerson } from './AdmissionRequestPerson';
import {
    AdmissionRequestPersonFromJSON,
    AdmissionRequestPersonFromJSONTyped,
    AdmissionRequestPersonToJSON,
    AdmissionRequestPersonToJSONTyped,
} from './AdmissionRequestPerson';

/**
 * 
 * @export
 * @interface AdmissionRequest
 */
export interface AdmissionRequest {
    /**
     * Unique identifier for the admission request (Event ID)
     * @type {number}
     * @memberof AdmissionRequest
     */
    id: number;
    /**
     * Current status of the admission request:
     * - pending: Waiting for door controller response
     * - admitted: Person successfully admitted (event codes 15, 16, 50)
     * - denied: Access denied (event code 51)
     * - offline: Door controller offline (event code 52)
     * - timeout: No response received within 2 minutes
     * 
     * @type {string}
     * @memberof AdmissionRequest
     */
    status: AdmissionRequestStatusEnum;
    /**
     * ID of the channel (door controller)
     * @type {number}
     * @memberof AdmissionRequest
     */
    channelId: number;
    /**
     * ID of the person (null for general admit requests)
     * @type {number}
     * @memberof AdmissionRequest
     */
    personId?: number | null;
    /**
     * Timestamp when the admission was requested
     * @type {Date}
     * @memberof AdmissionRequest
     */
    requestedAt: Date;
    /**
     * Timestamp when the admission completed (null if still pending)
     * @type {Date}
     * @memberof AdmissionRequest
     */
    completedAt?: Date | null;
    /**
     * 
     * @type {AdmissionRequestDoorController}
     * @memberof AdmissionRequest
     */
    doorController: AdmissionRequestDoorController;
    /**
     * 
     * @type {AdmissionRequestPerson}
     * @memberof AdmissionRequest
     */
    person?: AdmissionRequestPerson | null;
}


/**
 * @export
 */
export const AdmissionRequestStatusEnum = {
    Pending: 'pending',
    Admitted: 'admitted',
    Denied: 'denied',
    Offline: 'offline',
    Timeout: 'timeout'
} as const;
export type AdmissionRequestStatusEnum = typeof AdmissionRequestStatusEnum[keyof typeof AdmissionRequestStatusEnum];


/**
 * Check if a given object implements the AdmissionRequest interface.
 */
export function instanceOfAdmissionRequest(value: object): value is AdmissionRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('channelId' in value) || value['channelId'] === undefined) return false;
    if (!('requestedAt' in value) || value['requestedAt'] === undefined) return false;
    if (!('doorController' in value) || value['doorController'] === undefined) return false;
    return true;
}

export function AdmissionRequestFromJSON(json: any): AdmissionRequest {
    return AdmissionRequestFromJSONTyped(json, false);
}

export function AdmissionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdmissionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'channelId': json['channel_id'],
        'personId': json['person_id'] == null ? undefined : json['person_id'],
        'requestedAt': (new Date(json['requested_at'])),
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'doorController': AdmissionRequestDoorControllerFromJSON(json['door_controller']),
        'person': json['person'] == null ? undefined : AdmissionRequestPersonFromJSON(json['person']),
    };
}

export function AdmissionRequestToJSON(json: any): AdmissionRequest {
    return AdmissionRequestToJSONTyped(json, false);
}

export function AdmissionRequestToJSONTyped(value?: AdmissionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'channel_id': value['channelId'],
        'person_id': value['personId'],
        'requested_at': value['requestedAt'].toISOString(),
        'completed_at': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'door_controller': AdmissionRequestDoorControllerToJSON(value['doorController']),
        'person': AdmissionRequestPersonToJSON(value['person']),
    };
}

