/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdmitPersonRequest
 */
export interface AdmitPersonRequest {
    /**
     * ID of the person to admit
     * @type {number}
     * @memberof AdmitPersonRequest
     */
    personId: number;
}

/**
 * Check if a given object implements the AdmitPersonRequest interface.
 */
export function instanceOfAdmitPersonRequest(value: object): value is AdmitPersonRequest {
    if (!('personId' in value) || value['personId'] === undefined) return false;
    return true;
}

export function AdmitPersonRequestFromJSON(json: any): AdmitPersonRequest {
    return AdmitPersonRequestFromJSONTyped(json, false);
}

export function AdmitPersonRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdmitPersonRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'personId': json['person_id'],
    };
}

export function AdmitPersonRequestToJSON(json: any): AdmitPersonRequest {
    return AdmitPersonRequestToJSONTyped(json, false);
}

export function AdmitPersonRequestToJSONTyped(value?: AdmitPersonRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'person_id': value['personId'],
    };
}

