/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Information about the door controller
 * @export
 * @interface AdmissionRequestDoorController
 */
export interface AdmissionRequestDoorController {
    /**
     * Door controller ID
     * @type {number}
     * @memberof AdmissionRequestDoorController
     */
    id?: number;
    /**
     * Door controller name
     * @type {string}
     * @memberof AdmissionRequestDoorController
     */
    name?: string;
}

/**
 * Check if a given object implements the AdmissionRequestDoorController interface.
 */
export function instanceOfAdmissionRequestDoorController(value: object): value is AdmissionRequestDoorController {
    return true;
}

export function AdmissionRequestDoorControllerFromJSON(json: any): AdmissionRequestDoorController {
    return AdmissionRequestDoorControllerFromJSONTyped(json, false);
}

export function AdmissionRequestDoorControllerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdmissionRequestDoorController {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function AdmissionRequestDoorControllerToJSON(json: any): AdmissionRequestDoorController {
    return AdmissionRequestDoorControllerToJSONTyped(json, false);
}

export function AdmissionRequestDoorControllerToJSONTyped(value?: AdmissionRequestDoorController | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

