/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdmitChannel202Response
 */
export interface AdmitChannel202Response {
    /**
     * ID of the admission request (Event ID) for status tracking
     * @type {number}
     * @memberof AdmitChannel202Response
     */
    admissionRequestId?: number;
    /**
     * Initial status of the admission request
     * @type {string}
     * @memberof AdmitChannel202Response
     */
    status?: AdmitChannel202ResponseStatusEnum;
}


/**
 * @export
 */
export const AdmitChannel202ResponseStatusEnum = {
    Pending: 'pending',
    Admitted: 'admitted',
    Denied: 'denied',
    Offline: 'offline'
} as const;
export type AdmitChannel202ResponseStatusEnum = typeof AdmitChannel202ResponseStatusEnum[keyof typeof AdmitChannel202ResponseStatusEnum];


/**
 * Check if a given object implements the AdmitChannel202Response interface.
 */
export function instanceOfAdmitChannel202Response(value: object): value is AdmitChannel202Response {
    return true;
}

export function AdmitChannel202ResponseFromJSON(json: any): AdmitChannel202Response {
    return AdmitChannel202ResponseFromJSONTyped(json, false);
}

export function AdmitChannel202ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdmitChannel202Response {
    if (json == null) {
        return json;
    }
    return {
        
        'admissionRequestId': json['admission_request_id'] == null ? undefined : json['admission_request_id'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function AdmitChannel202ResponseToJSON(json: any): AdmitChannel202Response {
    return AdmitChannel202ResponseToJSONTyped(json, false);
}

export function AdmitChannel202ResponseToJSONTyped(value?: AdmitChannel202Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'admission_request_id': value['admissionRequestId'],
        'status': value['status'],
    };
}

