/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdmitPerson403Response
 */
export interface AdmitPerson403Response {
    /**
     * 
     * @type {string}
     * @memberof AdmitPerson403Response
     */
    error?: string;
    /**
     * Reason for denial
     * @type {string}
     * @memberof AdmitPerson403Response
     */
    reason?: string;
}

/**
 * Check if a given object implements the AdmitPerson403Response interface.
 */
export function instanceOfAdmitPerson403Response(value: object): value is AdmitPerson403Response {
    return true;
}

export function AdmitPerson403ResponseFromJSON(json: any): AdmitPerson403Response {
    return AdmitPerson403ResponseFromJSONTyped(json, false);
}

export function AdmitPerson403ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdmitPerson403Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function AdmitPerson403ResponseToJSON(json: any): AdmitPerson403Response {
    return AdmitPerson403ResponseToJSONTyped(json, false);
}

export function AdmitPerson403ResponseToJSONTyped(value?: AdmitPerson403Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'reason': value['reason'],
    };
}

