/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdmitPerson202Response
 */
export interface AdmitPerson202Response {
    /**
     * ID of the admission request for status tracking
     * @type {number}
     * @memberof AdmitPerson202Response
     */
    admissionRequestId?: number;
    /**
     * Initial status of the admission
     * @type {string}
     * @memberof AdmitPerson202Response
     */
    status?: AdmitPerson202ResponseStatusEnum;
}


/**
 * @export
 */
export const AdmitPerson202ResponseStatusEnum = {
    Pending: 'pending',
    Admitted: 'admitted',
    Denied: 'denied',
    Offline: 'offline'
} as const;
export type AdmitPerson202ResponseStatusEnum = typeof AdmitPerson202ResponseStatusEnum[keyof typeof AdmitPerson202ResponseStatusEnum];


/**
 * Check if a given object implements the AdmitPerson202Response interface.
 */
export function instanceOfAdmitPerson202Response(value: object): value is AdmitPerson202Response {
    return true;
}

export function AdmitPerson202ResponseFromJSON(json: any): AdmitPerson202Response {
    return AdmitPerson202ResponseFromJSONTyped(json, false);
}

export function AdmitPerson202ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdmitPerson202Response {
    if (json == null) {
        return json;
    }
    return {
        
        'admissionRequestId': json['admission_request_id'] == null ? undefined : json['admission_request_id'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function AdmitPerson202ResponseToJSON(json: any): AdmitPerson202Response {
    return AdmitPerson202ResponseToJSONTyped(json, false);
}

export function AdmitPerson202ResponseToJSONTyped(value?: AdmitPerson202Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'admission_request_id': value['admissionRequestId'],
        'status': value['status'],
    };
}

