/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Information about the person (null for general admit or if person not found)
 * @export
 * @interface AdmissionRequestPerson
 */
export interface AdmissionRequestPerson {
    /**
     * Person ID
     * @type {number}
     * @memberof AdmissionRequestPerson
     */
    id?: number;
    /**
     * Person name
     * @type {string}
     * @memberof AdmissionRequestPerson
     */
    name?: string;
}

/**
 * Check if a given object implements the AdmissionRequestPerson interface.
 */
export function instanceOfAdmissionRequestPerson(value: object): value is AdmissionRequestPerson {
    return true;
}

export function AdmissionRequestPersonFromJSON(json: any): AdmissionRequestPerson {
    return AdmissionRequestPersonFromJSONTyped(json, false);
}

export function AdmissionRequestPersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdmissionRequestPerson {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function AdmissionRequestPersonToJSON(json: any): AdmissionRequestPerson {
    return AdmissionRequestPersonToJSONTyped(json, false);
}

export function AdmissionRequestPersonToJSONTyped(value?: AdmissionRequestPerson | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

