/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Authenticate200Response
 */
export interface Authenticate200Response {
    /**
     * 
     * @type {boolean}
     * @memberof Authenticate200Response
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Authenticate200Response
     */
    apiKey?: string;
}

/**
 * Check if a given object implements the Authenticate200Response interface.
 */
export function instanceOfAuthenticate200Response(value: object): value is Authenticate200Response {
    return true;
}

export function Authenticate200ResponseFromJSON(json: any): Authenticate200Response {
    return Authenticate200ResponseFromJSONTyped(json, false);
}

export function Authenticate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Authenticate200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'apiKey': json['api_key'] == null ? undefined : json['api_key'],
    };
}

export function Authenticate200ResponseToJSON(json: any): Authenticate200Response {
    return Authenticate200ResponseToJSONTyped(json, false);
}

export function Authenticate200ResponseToJSONTyped(value?: Authenticate200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'api_key': value['apiKey'],
    };
}

