/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Authenticate401Response
 */
export interface Authenticate401Response {
    /**
     * 
     * @type {boolean}
     * @memberof Authenticate401Response
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Authenticate401Response
     */
    message?: string;
}

/**
 * Check if a given object implements the Authenticate401Response interface.
 */
export function instanceOfAuthenticate401Response(value: object): value is Authenticate401Response {
    return true;
}

export function Authenticate401ResponseFromJSON(json: any): Authenticate401Response {
    return Authenticate401ResponseFromJSONTyped(json, false);
}

export function Authenticate401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Authenticate401Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function Authenticate401ResponseToJSON(json: any): Authenticate401Response {
    return Authenticate401ResponseToJSONTyped(json, false);
}

export function Authenticate401ResponseToJSONTyped(value?: Authenticate401Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
    };
}

