/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticateRequest
 */
export interface AuthenticateRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthenticateRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticateRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the AuthenticateRequest interface.
 */
export function instanceOfAuthenticateRequest(value: object): value is AuthenticateRequest {
    return true;
}

export function AuthenticateRequestFromJSON(json: any): AuthenticateRequest {
    return AuthenticateRequestFromJSONTyped(json, false);
}

export function AuthenticateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function AuthenticateRequestToJSON(json: any): AuthenticateRequest {
    return AuthenticateRequestToJSONTyped(json, false);
}

export function AuthenticateRequestToJSONTyped(value?: AuthenticateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

