/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AutoUnlockChannel400Response
 */
export interface AutoUnlockChannel400Response {
    /**
     * 
     * @type {boolean}
     * @memberof AutoUnlockChannel400Response
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AutoUnlockChannel400Response
     */
    message?: string;
}

/**
 * Check if a given object implements the AutoUnlockChannel400Response interface.
 */
export function instanceOfAutoUnlockChannel400Response(value: object): value is AutoUnlockChannel400Response {
    return true;
}

export function AutoUnlockChannel400ResponseFromJSON(json: any): AutoUnlockChannel400Response {
    return AutoUnlockChannel400ResponseFromJSONTyped(json, false);
}

export function AutoUnlockChannel400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutoUnlockChannel400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function AutoUnlockChannel400ResponseToJSON(json: any): AutoUnlockChannel400Response {
    return AutoUnlockChannel400ResponseToJSONTyped(json, false);
}

export function AutoUnlockChannel400ResponseToJSONTyped(value?: AutoUnlockChannel400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
    };
}

