/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AutoUnlockChannelRequest
 */
export interface AutoUnlockChannelRequest {
    /**
     * ID of shift for auto-unlock (null or omit to disable)
     * @type {number}
     * @memberof AutoUnlockChannelRequest
     */
    shiftId?: number | null;
}

/**
 * Check if a given object implements the AutoUnlockChannelRequest interface.
 */
export function instanceOfAutoUnlockChannelRequest(value: object): value is AutoUnlockChannelRequest {
    return true;
}

export function AutoUnlockChannelRequestFromJSON(json: any): AutoUnlockChannelRequest {
    return AutoUnlockChannelRequestFromJSONTyped(json, false);
}

export function AutoUnlockChannelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutoUnlockChannelRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'shiftId': json['shift_id'] == null ? undefined : json['shift_id'],
    };
}

export function AutoUnlockChannelRequestToJSON(json: any): AutoUnlockChannelRequest {
    return AutoUnlockChannelRequestToJSONTyped(json, false);
}

export function AutoUnlockChannelRequestToJSONTyped(value?: AutoUnlockChannelRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'shift_id': value['shiftId'],
    };
}

