/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Association between Beacons and Door Controllers.
 * @export
 * @interface BeaconDoorController
 */
export interface BeaconDoorController {
    /**
     * 
     * @type {number}
     * @memberof BeaconDoorController
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof BeaconDoorController
     */
    threshold: BeaconDoorControllerThresholdEnum;
}


/**
 * @export
 */
export const BeaconDoorControllerThresholdEnum = {
    Far: 'Far',
    Near: 'Near',
    Immediate: 'Immediate'
} as const;
export type BeaconDoorControllerThresholdEnum = typeof BeaconDoorControllerThresholdEnum[keyof typeof BeaconDoorControllerThresholdEnum];


/**
 * Check if a given object implements the BeaconDoorController interface.
 */
export function instanceOfBeaconDoorController(value: object): value is BeaconDoorController {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('threshold' in value) || value['threshold'] === undefined) return false;
    return true;
}

export function BeaconDoorControllerFromJSON(json: any): BeaconDoorController {
    return BeaconDoorControllerFromJSONTyped(json, false);
}

export function BeaconDoorControllerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BeaconDoorController {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'threshold': json['threshold'],
    };
}

export function BeaconDoorControllerToJSON(json: any): BeaconDoorController {
    return BeaconDoorControllerToJSONTyped(json, false);
}

export function BeaconDoorControllerToJSONTyped(value?: BeaconDoorController | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'threshold': value['threshold'],
    };
}

