/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BeaconDoorController } from './BeaconDoorController';
import {
    BeaconDoorControllerFromJSON,
    BeaconDoorControllerFromJSONTyped,
    BeaconDoorControllerToJSON,
    BeaconDoorControllerToJSONTyped,
} from './BeaconDoorController';

/**
 * Beacon.
 * @export
 * @interface Beacon
 */
export interface Beacon {
    /**
     * 
     * @type {number}
     * @memberof Beacon
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Beacon
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Beacon
     */
    mode: number;
    /**
     * 
     * @type {string}
     * @memberof Beacon
     */
    uuid: string;
    /**
     * 
     * @type {number}
     * @memberof Beacon
     */
    major: number;
    /**
     * 
     * @type {number}
     * @memberof Beacon
     */
    minor: number;
    /**
     * 
     * @type {Set<BeaconDoorController>}
     * @memberof Beacon
     */
    doorControllers: Set<BeaconDoorController>;
}

/**
 * Check if a given object implements the Beacon interface.
 */
export function instanceOfBeacon(value: object): value is Beacon {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('major' in value) || value['major'] === undefined) return false;
    if (!('minor' in value) || value['minor'] === undefined) return false;
    if (!('doorControllers' in value) || value['doorControllers'] === undefined) return false;
    return true;
}

export function BeaconFromJSON(json: any): Beacon {
    return BeaconFromJSONTyped(json, false);
}

export function BeaconFromJSONTyped(json: any, ignoreDiscriminator: boolean): Beacon {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'mode': json['mode'],
        'uuid': json['uuid'],
        'major': json['major'],
        'minor': json['minor'],
        'doorControllers': (new Set((json['door_controllers'] as Array<any>).map(BeaconDoorControllerFromJSON))),
    };
}

export function BeaconToJSON(json: any): Beacon {
    return BeaconToJSONTyped(json, false);
}

export function BeaconToJSONTyped(value?: Beacon | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'mode': value['mode'],
        'uuid': value['uuid'],
        'major': value['major'],
        'minor': value['minor'],
        'door_controllers': (Array.from(value['doorControllers'] as Set<any>).map(BeaconDoorControllerToJSON)),
    };
}

