/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Current operating mode of the channel
 * @export
 * @interface ChannelMode
 */
export interface ChannelMode {
    /**
     * Current mode
     * @type {string}
     * @memberof ChannelMode
     */
    description: ChannelModeDescriptionEnum;
    /**
     * Time when door will automatically relock (if in unlock mode)
     * @type {Date}
     * @memberof ChannelMode
     */
    relockAt?: Date | null;
    /**
     * Timestamp when mode was last changed
     * @type {Date}
     * @memberof ChannelMode
     */
    changeStamp?: Date | null;
}


/**
 * @export
 */
export const ChannelModeDescriptionEnum = {
    Unlock: 'unlock',
    Normal: 'normal'
} as const;
export type ChannelModeDescriptionEnum = typeof ChannelModeDescriptionEnum[keyof typeof ChannelModeDescriptionEnum];


/**
 * Check if a given object implements the ChannelMode interface.
 */
export function instanceOfChannelMode(value: object): value is ChannelMode {
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function ChannelModeFromJSON(json: any): ChannelMode {
    return ChannelModeFromJSONTyped(json, false);
}

export function ChannelModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelMode {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'relockAt': json['relock_at'] == null ? undefined : (new Date(json['relock_at'])),
        'changeStamp': json['change_stamp'] == null ? undefined : (new Date(json['change_stamp'])),
    };
}

export function ChannelModeToJSON(json: any): ChannelMode {
    return ChannelModeToJSONTyped(json, false);
}

export function ChannelModeToJSONTyped(value?: ChannelMode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'relock_at': value['relockAt'] == null ? value['relockAt'] : value['relockAt'].toISOString(),
        'change_stamp': value['changeStamp'] == null ? value['changeStamp'] : value['changeStamp'].toISOString(),
    };
}

