/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Auto-unlock shift configuration (null if not configured)
 * @export
 * @interface ChannelAutoUnlock
 */
export interface ChannelAutoUnlock {
    /**
     * Shift ID
     * @type {number}
     * @memberof ChannelAutoUnlock
     */
    id?: number;
    /**
     * Shift name
     * @type {string}
     * @memberof ChannelAutoUnlock
     */
    name?: string;
}

/**
 * Check if a given object implements the ChannelAutoUnlock interface.
 */
export function instanceOfChannelAutoUnlock(value: object): value is ChannelAutoUnlock {
    return true;
}

export function ChannelAutoUnlockFromJSON(json: any): ChannelAutoUnlock {
    return ChannelAutoUnlockFromJSONTyped(json, false);
}

export function ChannelAutoUnlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelAutoUnlock {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ChannelAutoUnlockToJSON(json: any): ChannelAutoUnlock {
    return ChannelAutoUnlockToJSONTyped(json, false);
}

export function ChannelAutoUnlockToJSONTyped(value?: ChannelAutoUnlock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

