/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChannelLockdownCardLockdown
 */
export interface ChannelLockdownCardLockdown {
    /**
     * Whether card access is locked down
     * @type {boolean}
     * @memberof ChannelLockdownCardLockdown
     */
    state?: boolean;
}

/**
 * Check if a given object implements the ChannelLockdownCardLockdown interface.
 */
export function instanceOfChannelLockdownCardLockdown(value: object): value is ChannelLockdownCardLockdown {
    return true;
}

export function ChannelLockdownCardLockdownFromJSON(json: any): ChannelLockdownCardLockdown {
    return ChannelLockdownCardLockdownFromJSONTyped(json, false);
}

export function ChannelLockdownCardLockdownFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelLockdownCardLockdown {
    if (json == null) {
        return json;
    }
    return {
        
        'state': json['state'] == null ? undefined : json['state'],
    };
}

export function ChannelLockdownCardLockdownToJSON(json: any): ChannelLockdownCardLockdown {
    return ChannelLockdownCardLockdownToJSONTyped(json, false);
}

export function ChannelLockdownCardLockdownToJSONTyped(value?: ChannelLockdownCardLockdown | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'state': value['state'],
    };
}

