/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChannelLockdownRexLockdown } from './ChannelLockdownRexLockdown';
import {
    ChannelLockdownRexLockdownFromJSON,
    ChannelLockdownRexLockdownFromJSONTyped,
    ChannelLockdownRexLockdownToJSON,
    ChannelLockdownRexLockdownToJSONTyped,
} from './ChannelLockdownRexLockdown';
import type { ChannelLockdownAuxLockdown } from './ChannelLockdownAuxLockdown';
import {
    ChannelLockdownAuxLockdownFromJSON,
    ChannelLockdownAuxLockdownFromJSONTyped,
    ChannelLockdownAuxLockdownToJSON,
    ChannelLockdownAuxLockdownToJSONTyped,
} from './ChannelLockdownAuxLockdown';
import type { ChannelLockdownCardLockdown } from './ChannelLockdownCardLockdown';
import {
    ChannelLockdownCardLockdownFromJSON,
    ChannelLockdownCardLockdownFromJSONTyped,
    ChannelLockdownCardLockdownToJSON,
    ChannelLockdownCardLockdownToJSONTyped,
} from './ChannelLockdownCardLockdown';

/**
 * Lockdown mode configuration (null if not in lockdown)
 * @export
 * @interface ChannelLockdown
 */
export interface ChannelLockdown {
    /**
     * Lockdown status message
     * @type {string}
     * @memberof ChannelLockdown
     */
    message?: string;
    /**
     * 
     * @type {ChannelLockdownCardLockdown}
     * @memberof ChannelLockdown
     */
    cardLockdown?: ChannelLockdownCardLockdown;
    /**
     * 
     * @type {ChannelLockdownRexLockdown}
     * @memberof ChannelLockdown
     */
    rexLockdown?: ChannelLockdownRexLockdown;
    /**
     * 
     * @type {ChannelLockdownAuxLockdown}
     * @memberof ChannelLockdown
     */
    auxLockdown?: ChannelLockdownAuxLockdown;
}

/**
 * Check if a given object implements the ChannelLockdown interface.
 */
export function instanceOfChannelLockdown(value: object): value is ChannelLockdown {
    return true;
}

export function ChannelLockdownFromJSON(json: any): ChannelLockdown {
    return ChannelLockdownFromJSONTyped(json, false);
}

export function ChannelLockdownFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelLockdown {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'cardLockdown': json['card_lockdown'] == null ? undefined : ChannelLockdownCardLockdownFromJSON(json['card_lockdown']),
        'rexLockdown': json['rex_lockdown'] == null ? undefined : ChannelLockdownRexLockdownFromJSON(json['rex_lockdown']),
        'auxLockdown': json['aux_lockdown'] == null ? undefined : ChannelLockdownAuxLockdownFromJSON(json['aux_lockdown']),
    };
}

export function ChannelLockdownToJSON(json: any): ChannelLockdown {
    return ChannelLockdownToJSONTyped(json, false);
}

export function ChannelLockdownToJSONTyped(value?: ChannelLockdown | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'card_lockdown': ChannelLockdownCardLockdownToJSON(value['cardLockdown']),
        'rex_lockdown': ChannelLockdownRexLockdownToJSON(value['rexLockdown']),
        'aux_lockdown': ChannelLockdownAuxLockdownToJSON(value['auxLockdown']),
    };
}

