/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChannelLockdownRexLockdown
 */
export interface ChannelLockdownRexLockdown {
    /**
     * Whether REX (Request to Exit) is locked down
     * @type {boolean}
     * @memberof ChannelLockdownRexLockdown
     */
    state?: boolean;
}

/**
 * Check if a given object implements the ChannelLockdownRexLockdown interface.
 */
export function instanceOfChannelLockdownRexLockdown(value: object): value is ChannelLockdownRexLockdown {
    return true;
}

export function ChannelLockdownRexLockdownFromJSON(json: any): ChannelLockdownRexLockdown {
    return ChannelLockdownRexLockdownFromJSONTyped(json, false);
}

export function ChannelLockdownRexLockdownFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelLockdownRexLockdown {
    if (json == null) {
        return json;
    }
    return {
        
        'state': json['state'] == null ? undefined : json['state'],
    };
}

export function ChannelLockdownRexLockdownToJSON(json: any): ChannelLockdownRexLockdown {
    return ChannelLockdownRexLockdownToJSONTyped(json, false);
}

export function ChannelLockdownRexLockdownToJSONTyped(value?: ChannelLockdownRexLockdown | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'state': value['state'],
    };
}

