/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Synchronization status information
 * @export
 * @interface ChannelSync
 */
export interface ChannelSync {
    /**
     * Current sync status
     * @type {string}
     * @memberof ChannelSync
     */
    status: ChannelSyncStatusEnum;
    /**
     * Timestamp of last successful sync completion
     * @type {Date}
     * @memberof ChannelSync
     */
    lastSyncCompletedAt: Date | null;
}


/**
 * @export
 */
export const ChannelSyncStatusEnum = {
    Ok: 'ok',
    Fail: 'fail',
    Syncing: 'syncing',
    Pending: 'pending'
} as const;
export type ChannelSyncStatusEnum = typeof ChannelSyncStatusEnum[keyof typeof ChannelSyncStatusEnum];


/**
 * Check if a given object implements the ChannelSync interface.
 */
export function instanceOfChannelSync(value: object): value is ChannelSync {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('lastSyncCompletedAt' in value) || value['lastSyncCompletedAt'] === undefined) return false;
    return true;
}

export function ChannelSyncFromJSON(json: any): ChannelSync {
    return ChannelSyncFromJSONTyped(json, false);
}

export function ChannelSyncFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelSync {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'lastSyncCompletedAt': (json['last_sync_completed_at'] == null ? null : new Date(json['last_sync_completed_at'])),
    };
}

export function ChannelSyncToJSON(json: any): ChannelSync {
    return ChannelSyncToJSONTyped(json, false);
}

export function ChannelSyncToJSONTyped(value?: ChannelSync | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'last_sync_completed_at': value['lastSyncCompletedAt'] == null ? value['lastSyncCompletedAt'] : value['lastSyncCompletedAt'].toISOString(),
    };
}

