/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChannelLockdownAuxLockdown
 */
export interface ChannelLockdownAuxLockdown {
    /**
     * Whether auxiliary input is locked down
     * @type {boolean}
     * @memberof ChannelLockdownAuxLockdown
     */
    state?: boolean;
}

/**
 * Check if a given object implements the ChannelLockdownAuxLockdown interface.
 */
export function instanceOfChannelLockdownAuxLockdown(value: object): value is ChannelLockdownAuxLockdown {
    return true;
}

export function ChannelLockdownAuxLockdownFromJSON(json: any): ChannelLockdownAuxLockdown {
    return ChannelLockdownAuxLockdownFromJSONTyped(json, false);
}

export function ChannelLockdownAuxLockdownFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelLockdownAuxLockdown {
    if (json == null) {
        return json;
    }
    return {
        
        'state': json['state'] == null ? undefined : json['state'],
    };
}

export function ChannelLockdownAuxLockdownToJSON(json: any): ChannelLockdownAuxLockdown {
    return ChannelLockdownAuxLockdownToJSONTyped(json, false);
}

export function ChannelLockdownAuxLockdownToJSONTyped(value?: ChannelLockdownAuxLockdown | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'state': value['state'],
    };
}

