/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Field-specific validation errors
 * @export
 * @interface CreateCredential422ResponseErrors
 */
export interface CreateCredential422ResponseErrors {
    /**
     * Validation errors for the credential value
     * @type {Array<string>}
     * @memberof CreateCredential422ResponseErrors
     */
    value?: Array<string>;
    /**
     * Validation errors for the credential type
     * @type {Array<string>}
     * @memberof CreateCredential422ResponseErrors
     */
    credentialTypeId?: Array<string>;
    /**
     * License limit error message
     * @type {string}
     * @memberof CreateCredential422ResponseErrors
     */
    limitReached?: string;
}

/**
 * Check if a given object implements the CreateCredential422ResponseErrors interface.
 */
export function instanceOfCreateCredential422ResponseErrors(value: object): value is CreateCredential422ResponseErrors {
    return true;
}

export function CreateCredential422ResponseErrorsFromJSON(json: any): CreateCredential422ResponseErrors {
    return CreateCredential422ResponseErrorsFromJSONTyped(json, false);
}

export function CreateCredential422ResponseErrorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCredential422ResponseErrors {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
        'credentialTypeId': json['credential_type_id'] == null ? undefined : json['credential_type_id'],
        'limitReached': json['limit_reached'] == null ? undefined : json['limit_reached'],
    };
}

export function CreateCredential422ResponseErrorsToJSON(json: any): CreateCredential422ResponseErrors {
    return CreateCredential422ResponseErrorsToJSONTyped(json, false);
}

export function CreateCredential422ResponseErrorsToJSONTyped(value?: CreateCredential422ResponseErrors | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'credential_type_id': value['credentialTypeId'],
        'limit_reached': value['limitReached'],
    };
}

