/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateCredential422ResponseErrors } from './CreateCredential422ResponseErrors';
import {
    CreateCredential422ResponseErrorsFromJSON,
    CreateCredential422ResponseErrorsFromJSONTyped,
    CreateCredential422ResponseErrorsToJSON,
    CreateCredential422ResponseErrorsToJSONTyped,
} from './CreateCredential422ResponseErrors';

/**
 * 
 * @export
 * @interface CreateCredential422Response
 */
export interface CreateCredential422Response {
    /**
     * Error message
     * @type {string}
     * @memberof CreateCredential422Response
     */
    error?: string;
    /**
     * 
     * @type {CreateCredential422ResponseErrors}
     * @memberof CreateCredential422Response
     */
    errors?: CreateCredential422ResponseErrors;
}

/**
 * Check if a given object implements the CreateCredential422Response interface.
 */
export function instanceOfCreateCredential422Response(value: object): value is CreateCredential422Response {
    return true;
}

export function CreateCredential422ResponseFromJSON(json: any): CreateCredential422Response {
    return CreateCredential422ResponseFromJSONTyped(json, false);
}

export function CreateCredential422ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCredential422Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'errors': json['errors'] == null ? undefined : CreateCredential422ResponseErrorsFromJSON(json['errors']),
    };
}

export function CreateCredential422ResponseToJSON(json: any): CreateCredential422Response {
    return CreateCredential422ResponseToJSONTyped(json, false);
}

export function CreateCredential422ResponseToJSONTyped(value?: CreateCredential422Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'errors': CreateCredential422ResponseErrorsToJSON(value['errors']),
    };
}

