/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CredentialUpdateInputPersonCredential } from './CredentialUpdateInputPersonCredential';
import {
    CredentialUpdateInputPersonCredentialFromJSON,
    CredentialUpdateInputPersonCredentialFromJSONTyped,
    CredentialUpdateInputPersonCredentialToJSON,
    CredentialUpdateInputPersonCredentialToJSONTyped,
} from './CredentialUpdateInputPersonCredential';

/**
 * 
 * @export
 * @interface CredentialUpdateInput
 */
export interface CredentialUpdateInput {
    /**
     * 
     * @type {CredentialUpdateInputPersonCredential}
     * @memberof CredentialUpdateInput
     */
    personCredential: CredentialUpdateInputPersonCredential;
}

/**
 * Check if a given object implements the CredentialUpdateInput interface.
 */
export function instanceOfCredentialUpdateInput(value: object): value is CredentialUpdateInput {
    if (!('personCredential' in value) || value['personCredential'] === undefined) return false;
    return true;
}

export function CredentialUpdateInputFromJSON(json: any): CredentialUpdateInput {
    return CredentialUpdateInputFromJSONTyped(json, false);
}

export function CredentialUpdateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialUpdateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'personCredential': CredentialUpdateInputPersonCredentialFromJSON(json['person_credential']),
    };
}

export function CredentialUpdateInputToJSON(json: any): CredentialUpdateInput {
    return CredentialUpdateInputToJSONTyped(json, false);
}

export function CredentialUpdateInputToJSONTyped(value?: CredentialUpdateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'person_credential': CredentialUpdateInputPersonCredentialToJSON(value['personCredential']),
    };
}

