/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CredentialUpdateInputPersonCredential
 */
export interface CredentialUpdateInputPersonCredential {
    /**
     * New credential value
     * @type {string}
     * @memberof CredentialUpdateInputPersonCredential
     */
    value: string;
}

/**
 * Check if a given object implements the CredentialUpdateInputPersonCredential interface.
 */
export function instanceOfCredentialUpdateInputPersonCredential(value: object): value is CredentialUpdateInputPersonCredential {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function CredentialUpdateInputPersonCredentialFromJSON(json: any): CredentialUpdateInputPersonCredential {
    return CredentialUpdateInputPersonCredentialFromJSONTyped(json, false);
}

export function CredentialUpdateInputPersonCredentialFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialUpdateInputPersonCredential {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
    };
}

export function CredentialUpdateInputPersonCredentialToJSON(json: any): CredentialUpdateInputPersonCredential {
    return CredentialUpdateInputPersonCredentialToJSONTyped(json, false);
}

export function CredentialUpdateInputPersonCredentialToJSONTyped(value?: CredentialUpdateInputPersonCredential | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
    };
}

