/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CredentialInputPersonCredential
 */
export interface CredentialInputPersonCredential {
    /**
     * ID of the credential type (required)
     * @type {number}
     * @memberof CredentialInputPersonCredential
     */
    credentialTypeId: number;
    /**
     * Credential value (for card numbers, PINs, etc. Use "******" to auto-generate a random PIN)
     * @type {string}
     * @memberof CredentialInputPersonCredential
     */
    value?: string | null;
    /**
     * Person ID (typically derived from URL path parameter)
     * @type {number}
     * @memberof CredentialInputPersonCredential
     */
    personId?: number | null;
}

/**
 * Check if a given object implements the CredentialInputPersonCredential interface.
 */
export function instanceOfCredentialInputPersonCredential(value: object): value is CredentialInputPersonCredential {
    if (!('credentialTypeId' in value) || value['credentialTypeId'] === undefined) return false;
    return true;
}

export function CredentialInputPersonCredentialFromJSON(json: any): CredentialInputPersonCredential {
    return CredentialInputPersonCredentialFromJSONTyped(json, false);
}

export function CredentialInputPersonCredentialFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialInputPersonCredential {
    if (json == null) {
        return json;
    }
    return {
        
        'credentialTypeId': json['credential_type_id'],
        'value': json['value'] == null ? undefined : json['value'],
        'personId': json['person_id'] == null ? undefined : json['person_id'],
    };
}

export function CredentialInputPersonCredentialToJSON(json: any): CredentialInputPersonCredential {
    return CredentialInputPersonCredentialToJSONTyped(json, false);
}

export function CredentialInputPersonCredentialToJSONTyped(value?: CredentialInputPersonCredential | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'credential_type_id': value['credentialTypeId'],
        'value': value['value'],
        'person_id': value['personId'],
    };
}

