/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Account Credential Type.
 * @export
 * @interface CredentialType
 */
export interface CredentialType {
    /**
     * 
     * @type {number}
     * @memberof CredentialType
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof CredentialType
     */
    label: string;
}

/**
 * Check if a given object implements the CredentialType interface.
 */
export function instanceOfCredentialType(value: object): value is CredentialType {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function CredentialTypeFromJSON(json: any): CredentialType {
    return CredentialTypeFromJSONTyped(json, false);
}

export function CredentialTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'label': json['label'],
    };
}

export function CredentialTypeToJSON(json: any): CredentialType {
    return CredentialTypeToJSONTyped(json, false);
}

export function CredentialTypeToJSONTyped(value?: CredentialType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'label': value['label'],
    };
}

