/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CredentialType
 */
export interface CredentialType {
    /**
     * Unique identifier for the credential type
     * @type {number}
     * @memberof CredentialType
     */
    id: number;
    /**
     * Human-readable label for the credential type (must be unique within account)
     * @type {string}
     * @memberof CredentialType
     */
    label: string;
    /**
     * URL-friendly identifier used in API requests (must be unique within account, auto-parameterized)
     * @type {string}
     * @memberof CredentialType
     */
    slug: string;
    /**
     * Numeric code from the associated global credential type
     * @type {number}
     * @memberof CredentialType
     */
    code: number | null;
}

/**
 * Check if a given object implements the CredentialType interface.
 */
export function instanceOfCredentialType(value: object): value is CredentialType {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function CredentialTypeFromJSON(json: any): CredentialType {
    return CredentialTypeFromJSONTyped(json, false);
}

export function CredentialTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'label': json['label'],
        'slug': json['slug'],
        'code': json['code'],
    };
}

export function CredentialTypeToJSON(json: any): CredentialType {
    return CredentialTypeToJSONTyped(json, false);
}

export function CredentialTypeToJSONTyped(value?: CredentialType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'label': value['label'],
        'slug': value['slug'],
        'code': value['code'],
    };
}

