/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CredentialInputPersonCredential } from './CredentialInputPersonCredential';
import {
    CredentialInputPersonCredentialFromJSON,
    CredentialInputPersonCredentialFromJSONTyped,
    CredentialInputPersonCredentialToJSON,
    CredentialInputPersonCredentialToJSONTyped,
} from './CredentialInputPersonCredential';

/**
 * 
 * @export
 * @interface CredentialInput
 */
export interface CredentialInput {
    /**
     * 
     * @type {CredentialInputPersonCredential}
     * @memberof CredentialInput
     */
    personCredential: CredentialInputPersonCredential;
}

/**
 * Check if a given object implements the CredentialInput interface.
 */
export function instanceOfCredentialInput(value: object): value is CredentialInput {
    if (!('personCredential' in value) || value['personCredential'] === undefined) return false;
    return true;
}

export function CredentialInputFromJSON(json: any): CredentialInput {
    return CredentialInputFromJSONTyped(json, false);
}

export function CredentialInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CredentialInput {
    if (json == null) {
        return json;
    }
    return {
        
        'personCredential': CredentialInputPersonCredentialFromJSON(json['person_credential']),
    };
}

export function CredentialInputToJSON(json: any): CredentialInput {
    return CredentialInputToJSONTyped(json, false);
}

export function CredentialInputToJSONTyped(value?: CredentialInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'person_credential': CredentialInputPersonCredentialToJSON(value['personCredential']),
    };
}

