/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Credential
 */
export interface Credential {
    /**
     * Unique hashid identifier for the credential
     * @type {string}
     * @memberof Credential
     */
    id: string;
    /**
     * ID of the credential type
     * @type {number}
     * @memberof Credential
     */
    credentialTypeId: number;
    /**
     * Human-readable label for the credential type
     * @type {string}
     * @memberof Credential
     */
    label: string;
    /**
     * ID of the person this credential belongs to
     * @type {number}
     * @memberof Credential
     */
    personId: number;
    /**
     * Credential value (only present for value-assignable credential types like cards, PINs, etc. Not present for mobile credentials)
     * @type {string}
     * @memberof Credential
     */
    value?: string | null;
    /**
     * Status for mobile credentials (HID Mobile Access)
     * @type {string}
     * @memberof Credential
     */
    status?: CredentialStatusEnum | null;
    /**
     * PassFlow credential URL (only for PassFlow credentials in invited state)
     * @type {string}
     * @memberof Credential
     */
    url?: string | null;
    /**
     * Wallet type for PassFlow credentials that have been added to wallet
     * @type {string}
     * @memberof Credential
     */
    walletType?: CredentialWalletTypeEnum | null;
}


/**
 * @export
 */
export const CredentialStatusEnum = {
    Invited: 'invited',
    Active: 'active',
    Revoking: 'revoking',
    Revoked: 'revoked'
} as const;
export type CredentialStatusEnum = typeof CredentialStatusEnum[keyof typeof CredentialStatusEnum];

/**
 * @export
 */
export const CredentialWalletTypeEnum = {
    Apple: 'apple',
    Google: 'google'
} as const;
export type CredentialWalletTypeEnum = typeof CredentialWalletTypeEnum[keyof typeof CredentialWalletTypeEnum];


/**
 * Check if a given object implements the Credential interface.
 */
export function instanceOfCredential(value: object): value is Credential {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('credentialTypeId' in value) || value['credentialTypeId'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('personId' in value) || value['personId'] === undefined) return false;
    return true;
}

export function CredentialFromJSON(json: any): Credential {
    return CredentialFromJSONTyped(json, false);
}

export function CredentialFromJSONTyped(json: any, ignoreDiscriminator: boolean): Credential {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'credentialTypeId': json['credential_type_id'],
        'label': json['label'],
        'personId': json['person_id'],
        'value': json['value'] == null ? undefined : json['value'],
        'status': json['status'] == null ? undefined : json['status'],
        'url': json['url'] == null ? undefined : json['url'],
        'walletType': json['wallet_type'] == null ? undefined : json['wallet_type'],
    };
}

export function CredentialToJSON(json: any): Credential {
    return CredentialToJSONTyped(json, false);
}

export function CredentialToJSONTyped(value?: Credential | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'credential_type_id': value['credentialTypeId'],
        'label': value['label'],
        'person_id': value['personId'],
        'value': value['value'],
        'status': value['status'],
        'url': value['url'],
        'wallet_type': value['walletType'],
    };
}

