/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteGroupReservation200Response
 */
export interface DeleteGroupReservation200Response {
    /**
     * 
     * @type {string}
     * @memberof DeleteGroupReservation200Response
     */
    result?: string;
}

/**
 * Check if a given object implements the DeleteGroupReservation200Response interface.
 */
export function instanceOfDeleteGroupReservation200Response(value: object): value is DeleteGroupReservation200Response {
    return true;
}

export function DeleteGroupReservation200ResponseFromJSON(json: any): DeleteGroupReservation200Response {
    return DeleteGroupReservation200ResponseFromJSONTyped(json, false);
}

export function DeleteGroupReservation200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteGroupReservation200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : json['result'],
    };
}

export function DeleteGroupReservation200ResponseToJSON(json: any): DeleteGroupReservation200Response {
    return DeleteGroupReservation200ResponseToJSONTyped(json, false);
}

export function DeleteGroupReservation200ResponseToJSONTyped(value?: DeleteGroupReservation200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'],
    };
}

