/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DoorControllerMode
 */
export interface DoorControllerMode {
    /**
     * 
     * @type {string}
     * @memberof DoorControllerMode
     */
    description: string;
    /**
     * 
     * @type {any}
     * @memberof DoorControllerMode
     */
    relockAt?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DoorControllerMode
     */
    changeStamp?: any | null;
}

/**
 * Check if a given object implements the DoorControllerMode interface.
 */
export function instanceOfDoorControllerMode(value: object): value is DoorControllerMode {
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function DoorControllerModeFromJSON(json: any): DoorControllerMode {
    return DoorControllerModeFromJSONTyped(json, false);
}

export function DoorControllerModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoorControllerMode {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'relockAt': json['relock_at'] == null ? undefined : json['relock_at'],
        'changeStamp': json['change_stamp'] == null ? undefined : json['change_stamp'],
    };
}

export function DoorControllerModeToJSON(json: any): DoorControllerMode {
    return DoorControllerModeToJSONTyped(json, false);
}

export function DoorControllerModeToJSONTyped(value?: DoorControllerMode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'relock_at': value['relockAt'],
        'change_stamp': value['changeStamp'],
    };
}

