/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DoorControllerSync
 */
export interface DoorControllerSync {
    /**
     * 
     * @type {string}
     * @memberof DoorControllerSync
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof DoorControllerSync
     */
    lastSyncCompletedAt: string;
}

/**
 * Check if a given object implements the DoorControllerSync interface.
 */
export function instanceOfDoorControllerSync(value: object): value is DoorControllerSync {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('lastSyncCompletedAt' in value) || value['lastSyncCompletedAt'] === undefined) return false;
    return true;
}

export function DoorControllerSyncFromJSON(json: any): DoorControllerSync {
    return DoorControllerSyncFromJSONTyped(json, false);
}

export function DoorControllerSyncFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoorControllerSync {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'lastSyncCompletedAt': json['last_sync_completed_at'],
    };
}

export function DoorControllerSyncToJSON(json: any): DoorControllerSync {
    return DoorControllerSyncToJSONTyped(json, false);
}

export function DoorControllerSyncToJSONTyped(value?: DoorControllerSync | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'last_sync_completed_at': value['lastSyncCompletedAt'],
    };
}

