/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DoorControllerSync } from './DoorControllerSync';
import {
    DoorControllerSyncFromJSON,
    DoorControllerSyncFromJSONTyped,
    DoorControllerSyncToJSON,
    DoorControllerSyncToJSONTyped,
} from './DoorControllerSync';
import type { DoorControllerMode } from './DoorControllerMode';
import {
    DoorControllerModeFromJSON,
    DoorControllerModeFromJSONTyped,
    DoorControllerModeToJSON,
    DoorControllerModeToJSONTyped,
} from './DoorControllerMode';

/**
 * 
 * @export
 * @interface DoorController
 */
export interface DoorController {
    /**
     * 
     * @type {number}
     * @memberof DoorController
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof DoorController
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DoorController
     */
    macAddress: string;
    /**
     * 
     * @type {string}
     * @memberof DoorController
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof DoorController
     */
    encryptionKey: string;
    /**
     * 
     * @type {number}
     * @memberof DoorController
     */
    unit: number;
    /**
     * 
     * @type {string}
     * @memberof DoorController
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof DoorController
     */
    modelLong: string;
    /**
     * 
     * @type {any}
     * @memberof DoorController
     */
    serialNumber?: any | null;
    /**
     * 
     * @type {string}
     * @memberof DoorController
     */
    cardFormat: string;
    /**
     * 
     * @type {string}
     * @memberof DoorController
     */
    pinFormat: string;
    /**
     * 
     * @type {string}
     * @memberof DoorController
     */
    freescaleVersion: string;
    /**
     * 
     * @type {string}
     * @memberof DoorController
     */
    picVersion: string;
    /**
     * 
     * @type {string}
     * @memberof DoorController
     */
    readerDeviceClassName: string;
    /**
     * 
     * @type {string}
     * @memberof DoorController
     */
    updatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof DoorController
     */
    createdAt: string;
    /**
     * 
     * @type {DoorControllerSync}
     * @memberof DoorController
     */
    sync: DoorControllerSync;
    /**
     * 
     * @type {any}
     * @memberof DoorController
     */
    lockdown?: any | null;
    /**
     * 
     * @type {DoorControllerMode}
     * @memberof DoorController
     */
    mode: DoorControllerMode;
    /**
     * 
     * @type {any}
     * @memberof DoorController
     */
    autoUnlock?: any | null;
}

/**
 * Check if a given object implements the DoorController interface.
 */
export function instanceOfDoorController(value: object): value is DoorController {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('macAddress' in value) || value['macAddress'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('encryptionKey' in value) || value['encryptionKey'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('modelLong' in value) || value['modelLong'] === undefined) return false;
    if (!('cardFormat' in value) || value['cardFormat'] === undefined) return false;
    if (!('pinFormat' in value) || value['pinFormat'] === undefined) return false;
    if (!('freescaleVersion' in value) || value['freescaleVersion'] === undefined) return false;
    if (!('picVersion' in value) || value['picVersion'] === undefined) return false;
    if (!('readerDeviceClassName' in value) || value['readerDeviceClassName'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('sync' in value) || value['sync'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    return true;
}

export function DoorControllerFromJSON(json: any): DoorController {
    return DoorControllerFromJSONTyped(json, false);
}

export function DoorControllerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoorController {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'macAddress': json['mac_address'],
        'status': json['status'],
        'encryptionKey': json['encryption_key'],
        'unit': json['unit'],
        'model': json['model'],
        'modelLong': json['model_long'],
        'serialNumber': json['serial_number'] == null ? undefined : json['serial_number'],
        'cardFormat': json['card_format'],
        'pinFormat': json['pin_format'],
        'freescaleVersion': json['freescale_version'],
        'picVersion': json['pic_version'],
        'readerDeviceClassName': json['reader_device_class_name'],
        'updatedAt': json['updated_at'],
        'createdAt': json['created_at'],
        'sync': DoorControllerSyncFromJSON(json['sync']),
        'lockdown': json['lockdown'] == null ? undefined : json['lockdown'],
        'mode': DoorControllerModeFromJSON(json['mode']),
        'autoUnlock': json['auto_unlock'] == null ? undefined : json['auto_unlock'],
    };
}

export function DoorControllerToJSON(json: any): DoorController {
    return DoorControllerToJSONTyped(json, false);
}

export function DoorControllerToJSONTyped(value?: DoorController | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'mac_address': value['macAddress'],
        'status': value['status'],
        'encryption_key': value['encryptionKey'],
        'unit': value['unit'],
        'model': value['model'],
        'model_long': value['modelLong'],
        'serial_number': value['serialNumber'],
        'card_format': value['cardFormat'],
        'pin_format': value['pinFormat'],
        'freescale_version': value['freescaleVersion'],
        'pic_version': value['picVersion'],
        'reader_device_class_name': value['readerDeviceClassName'],
        'updated_at': value['updatedAt'],
        'created_at': value['createdAt'],
        'sync': DoorControllerSyncToJSON(value['sync']),
        'lockdown': value['lockdown'],
        'mode': DoorControllerModeToJSON(value['mode']),
        'auto_unlock': value['autoUnlock'],
    };
}

