/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * Unique identifier for the event
     * @type {number}
     * @memberof Event
     */
    id: number;
    /**
     * Same as id (legacy field for backward compatibility)
     * @type {number}
     * @memberof Event
     */
    eventId?: number | null;
    /**
     * Numeric code identifying the event type. Common codes:
     * - 10-18: Admit events (card, PIN, manual, REX, AUX, application, unlocked, Apple, Google)
     * - 20-29: Reject events (card, out of hours, lockdown, tamper, PIN, timeout, invalid type, unauthorized, pass-back, offline)
     * - 30: REX pressed
     * - 31-37: Door state/alarm events
     * - 40-42: Auto-unlock shift events
     * - 50-63: Remote control events
     * - 70-73: Multi-factor authentication events
     * - 90-91: Tamper events
     * - 100-107: Channel sync events
     * 
     * @type {number}
     * @memberof Event
     */
    eventCode: number;
    /**
     * Human-readable description of the event
     * @type {string}
     * @memberof Event
     */
    eventLabel: string;
    /**
     * ID of the door controller (channel) where the event occurred
     * @type {number}
     * @memberof Event
     */
    doorControllerId?: number | null;
    /**
     * Name of the door controller (channel)
     * @type {string}
     * @memberof Event
     */
    doorControllerName?: string | null;
    /**
     * Alias for door_controller_id
     * @type {number}
     * @memberof Event
     */
    channelId?: number | null;
    /**
     * Alias for door_controller_name
     * @type {string}
     * @memberof Event
     */
    channelName?: string | null;
    /**
     * ID of the person associated with this event (for access events)
     * @type {number}
     * @memberof Event
     */
    personId?: number | null;
    /**
     * Name of the person associated with this event
     * @type {string}
     * @memberof Event
     */
    personName?: string | null;
    /**
     * Credential number used (card number, PIN, etc.)
     * @type {string}
     * @memberof Event
     */
    credentialsNumber?: string | null;
    /**
     * Timestamp when the event occurred
     * @type {Date}
     * @memberof Event
     */
    createdAt: Date;
    /**
     * Timestamp when the event record was last updated
     * @type {Date}
     * @memberof Event
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the Event interface.
 */
export function instanceOfEvent(value: object): value is Event {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('eventCode' in value) || value['eventCode'] === undefined) return false;
    if (!('eventLabel' in value) || value['eventLabel'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function EventFromJSON(json: any): Event {
    return EventFromJSONTyped(json, false);
}

export function EventFromJSONTyped(json: any, ignoreDiscriminator: boolean): Event {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'eventId': json['event_id'] == null ? undefined : json['event_id'],
        'eventCode': json['event_code'],
        'eventLabel': json['event_label'],
        'doorControllerId': json['door_controller_id'] == null ? undefined : json['door_controller_id'],
        'doorControllerName': json['door_controller_name'] == null ? undefined : json['door_controller_name'],
        'channelId': json['channel_id'] == null ? undefined : json['channel_id'],
        'channelName': json['channel_name'] == null ? undefined : json['channel_name'],
        'personId': json['person_id'] == null ? undefined : json['person_id'],
        'personName': json['person_name'] == null ? undefined : json['person_name'],
        'credentialsNumber': json['credentials_number'] == null ? undefined : json['credentials_number'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function EventToJSON(json: any): Event {
    return EventToJSONTyped(json, false);
}

export function EventToJSONTyped(value?: Event | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'event_id': value['eventId'],
        'event_code': value['eventCode'],
        'event_label': value['eventLabel'],
        'door_controller_id': value['doorControllerId'],
        'door_controller_name': value['doorControllerName'],
        'channel_id': value['channelId'],
        'channel_name': value['channelName'],
        'person_id': value['personId'],
        'person_name': value['personName'],
        'credentials_number': value['credentialsNumber'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

