/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAdmissionRequest500Response
 */
export interface GetAdmissionRequest500Response {
    /**
     * 
     * @type {string}
     * @memberof GetAdmissionRequest500Response
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAdmissionRequest500Response
     */
    errorDescription?: string;
}

/**
 * Check if a given object implements the GetAdmissionRequest500Response interface.
 */
export function instanceOfGetAdmissionRequest500Response(value: object): value is GetAdmissionRequest500Response {
    return true;
}

export function GetAdmissionRequest500ResponseFromJSON(json: any): GetAdmissionRequest500Response {
    return GetAdmissionRequest500ResponseFromJSONTyped(json, false);
}

export function GetAdmissionRequest500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAdmissionRequest500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'errorDescription': json['error_description'] == null ? undefined : json['error_description'],
    };
}

export function GetAdmissionRequest500ResponseToJSON(json: any): GetAdmissionRequest500Response {
    return GetAdmissionRequest500ResponseToJSONTyped(json, false);
}

export function GetAdmissionRequest500ResponseToJSONTyped(value?: GetAdmissionRequest500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'error_description': value['errorDescription'],
    };
}

