/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAdmissionRequest403Response
 */
export interface GetAdmissionRequest403Response {
    /**
     * 
     * @type {string}
     * @memberof GetAdmissionRequest403Response
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAdmissionRequest403Response
     */
    errorDescription?: string;
}

/**
 * Check if a given object implements the GetAdmissionRequest403Response interface.
 */
export function instanceOfGetAdmissionRequest403Response(value: object): value is GetAdmissionRequest403Response {
    return true;
}

export function GetAdmissionRequest403ResponseFromJSON(json: any): GetAdmissionRequest403Response {
    return GetAdmissionRequest403ResponseFromJSONTyped(json, false);
}

export function GetAdmissionRequest403ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAdmissionRequest403Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'errorDescription': json['error_description'] == null ? undefined : json['error_description'],
    };
}

export function GetAdmissionRequest403ResponseToJSON(json: any): GetAdmissionRequest403Response {
    return GetAdmissionRequest403ResponseToJSONTyped(json, false);
}

export function GetAdmissionRequest403ResponseToJSONTyped(value?: GetAdmissionRequest403Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'error_description': value['errorDescription'],
    };
}

