/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAccessToken400Response
 */
export interface GetAccessToken400Response {
    /**
     * 
     * @type {string}
     * @memberof GetAccessToken400Response
     */
    error?: GetAccessToken400ResponseErrorEnum;
    /**
     * 
     * @type {string}
     * @memberof GetAccessToken400Response
     */
    errorDescription?: string;
}


/**
 * @export
 */
export const GetAccessToken400ResponseErrorEnum = {
    InvalidRequest: 'invalid_request',
    InvalidGrant: 'invalid_grant',
    UnsupportedGrantType: 'unsupported_grant_type',
    InvalidScope: 'invalid_scope',
    InvalidClient: 'invalid_client'
} as const;
export type GetAccessToken400ResponseErrorEnum = typeof GetAccessToken400ResponseErrorEnum[keyof typeof GetAccessToken400ResponseErrorEnum];


/**
 * Check if a given object implements the GetAccessToken400Response interface.
 */
export function instanceOfGetAccessToken400Response(value: object): value is GetAccessToken400Response {
    return true;
}

export function GetAccessToken400ResponseFromJSON(json: any): GetAccessToken400Response {
    return GetAccessToken400ResponseFromJSONTyped(json, false);
}

export function GetAccessToken400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccessToken400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'errorDescription': json['error_description'] == null ? undefined : json['error_description'],
    };
}

export function GetAccessToken400ResponseToJSON(json: any): GetAccessToken400Response {
    return GetAccessToken400ResponseToJSONTyped(json, false);
}

export function GetAccessToken400ResponseToJSONTyped(value?: GetAccessToken400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'error_description': value['errorDescription'],
    };
}

