/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAccessToken200Response
 */
export interface GetAccessToken200Response {
    /**
     * Bearer token to use for API authentication
     * @type {string}
     * @memberof GetAccessToken200Response
     */
    accessToken: string;
    /**
     * Token type (always "Bearer")
     * @type {string}
     * @memberof GetAccessToken200Response
     */
    tokenType: string;
    /**
     * Number of seconds until the access token expires (3600 = 1 hour)
     * @type {number}
     * @memberof GetAccessToken200Response
     */
    expiresIn: number;
    /**
     * Refresh token to obtain a new access token (only included on initial token grant)
     * @type {string}
     * @memberof GetAccessToken200Response
     */
    refreshToken?: string;
    /**
     * Space-separated list of granted scopes
     * @type {string}
     * @memberof GetAccessToken200Response
     */
    scope?: string;
    /**
     * Unix timestamp when the token was created
     * @type {number}
     * @memberof GetAccessToken200Response
     */
    createdAt: number;
}

/**
 * Check if a given object implements the GetAccessToken200Response interface.
 */
export function instanceOfGetAccessToken200Response(value: object): value is GetAccessToken200Response {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('tokenType' in value) || value['tokenType'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function GetAccessToken200ResponseFromJSON(json: any): GetAccessToken200Response {
    return GetAccessToken200ResponseFromJSONTyped(json, false);
}

export function GetAccessToken200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccessToken200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'tokenType': json['token_type'],
        'expiresIn': json['expires_in'],
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'createdAt': json['created_at'],
    };
}

export function GetAccessToken200ResponseToJSON(json: any): GetAccessToken200Response {
    return GetAccessToken200ResponseToJSONTyped(json, false);
}

export function GetAccessToken200ResponseToJSONTyped(value?: GetAccessToken200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'token_type': value['tokenType'],
        'expires_in': value['expiresIn'],
        'refresh_token': value['refreshToken'],
        'scope': value['scope'],
        'created_at': value['createdAt'],
    };
}

