/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAdmissionRequest404Response
 */
export interface GetAdmissionRequest404Response {
    /**
     * 
     * @type {string}
     * @memberof GetAdmissionRequest404Response
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAdmissionRequest404Response
     */
    errorDescription?: string;
}

/**
 * Check if a given object implements the GetAdmissionRequest404Response interface.
 */
export function instanceOfGetAdmissionRequest404Response(value: object): value is GetAdmissionRequest404Response {
    return true;
}

export function GetAdmissionRequest404ResponseFromJSON(json: any): GetAdmissionRequest404Response {
    return GetAdmissionRequest404ResponseFromJSONTyped(json, false);
}

export function GetAdmissionRequest404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAdmissionRequest404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'errorDescription': json['error_description'] == null ? undefined : json['error_description'],
    };
}

export function GetAdmissionRequest404ResponseToJSON(json: any): GetAdmissionRequest404Response {
    return GetAdmissionRequest404ResponseToJSONTyped(json, false);
}

export function GetAdmissionRequest404ResponseToJSONTyped(value?: GetAdmissionRequest404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'error_description': value['errorDescription'],
    };
}

