/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetTokenInfo200ResponseApplication } from './GetTokenInfo200ResponseApplication';
import {
    GetTokenInfo200ResponseApplicationFromJSON,
    GetTokenInfo200ResponseApplicationFromJSONTyped,
    GetTokenInfo200ResponseApplicationToJSON,
    GetTokenInfo200ResponseApplicationToJSONTyped,
} from './GetTokenInfo200ResponseApplication';

/**
 * 
 * @export
 * @interface GetTokenInfo200Response
 */
export interface GetTokenInfo200Response {
    /**
     * ID of the user (resource owner) who authorized this token
     * @type {number}
     * @memberof GetTokenInfo200Response
     */
    resourceOwnerId: number;
    /**
     * Hashid of the account associated with the resource owner
     * @type {string}
     * @memberof GetTokenInfo200Response
     */
    accountId?: string;
    /**
     * Array of OAuth scopes granted to this token
     * @type {Array<string>}
     * @memberof GetTokenInfo200Response
     */
    scope: Array<string>;
    /**
     * Number of seconds until the token expires
     * @type {number}
     * @memberof GetTokenInfo200Response
     */
    expiresIn: number;
    /**
     * 
     * @type {GetTokenInfo200ResponseApplication}
     * @memberof GetTokenInfo200Response
     */
    application?: GetTokenInfo200ResponseApplication;
    /**
     * Unix timestamp when the token was created
     * @type {number}
     * @memberof GetTokenInfo200Response
     */
    createdAt: number;
}

/**
 * Check if a given object implements the GetTokenInfo200Response interface.
 */
export function instanceOfGetTokenInfo200Response(value: object): value is GetTokenInfo200Response {
    if (!('resourceOwnerId' in value) || value['resourceOwnerId'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function GetTokenInfo200ResponseFromJSON(json: any): GetTokenInfo200Response {
    return GetTokenInfo200ResponseFromJSONTyped(json, false);
}

export function GetTokenInfo200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTokenInfo200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceOwnerId': json['resource_owner_id'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'scope': json['scope'],
        'expiresIn': json['expires_in'],
        'application': json['application'] == null ? undefined : GetTokenInfo200ResponseApplicationFromJSON(json['application']),
        'createdAt': json['created_at'],
    };
}

export function GetTokenInfo200ResponseToJSON(json: any): GetTokenInfo200Response {
    return GetTokenInfo200ResponseToJSONTyped(json, false);
}

export function GetTokenInfo200ResponseToJSONTyped(value?: GetTokenInfo200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resource_owner_id': value['resourceOwnerId'],
        'account_id': value['accountId'],
        'scope': value['scope'],
        'expires_in': value['expiresIn'],
        'application': GetTokenInfo200ResponseApplicationToJSON(value['application']),
        'created_at': value['createdAt'],
    };
}

