/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetTokenInfo200ResponseApplication
 */
export interface GetTokenInfo200ResponseApplication {
    /**
     * Unique identifier of the OAuth application
     * @type {string}
     * @memberof GetTokenInfo200ResponseApplication
     */
    uid?: string;
}

/**
 * Check if a given object implements the GetTokenInfo200ResponseApplication interface.
 */
export function instanceOfGetTokenInfo200ResponseApplication(value: object): value is GetTokenInfo200ResponseApplication {
    return true;
}

export function GetTokenInfo200ResponseApplicationFromJSON(json: any): GetTokenInfo200ResponseApplication {
    return GetTokenInfo200ResponseApplicationFromJSONTyped(json, false);
}

export function GetTokenInfo200ResponseApplicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTokenInfo200ResponseApplication {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
    };
}

export function GetTokenInfo200ResponseApplicationToJSON(json: any): GetTokenInfo200ResponseApplication {
    return GetTokenInfo200ResponseApplicationToJSONTyped(json, false);
}

export function GetTokenInfo200ResponseApplicationToJSONTyped(value?: GetTokenInfo200ResponseApplication | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
    };
}

