/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetTokenInfo401Response
 */
export interface GetTokenInfo401Response {
    /**
     * 
     * @type {string}
     * @memberof GetTokenInfo401Response
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTokenInfo401Response
     */
    errorDescription?: string;
}

/**
 * Check if a given object implements the GetTokenInfo401Response interface.
 */
export function instanceOfGetTokenInfo401Response(value: object): value is GetTokenInfo401Response {
    return true;
}

export function GetTokenInfo401ResponseFromJSON(json: any): GetTokenInfo401Response {
    return GetTokenInfo401ResponseFromJSONTyped(json, false);
}

export function GetTokenInfo401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTokenInfo401Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'errorDescription': json['error_description'] == null ? undefined : json['error_description'],
    };
}

export function GetTokenInfo401ResponseToJSON(json: any): GetTokenInfo401Response {
    return GetTokenInfo401ResponseToJSONTyped(json, false);
}

export function GetTokenInfo401ResponseToJSONTyped(value?: GetTokenInfo401Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'error_description': value['errorDescription'],
    };
}

