/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupReservationInputGroupReservation } from './GroupReservationInputGroupReservation';
import {
    GroupReservationInputGroupReservationFromJSON,
    GroupReservationInputGroupReservationFromJSONTyped,
    GroupReservationInputGroupReservationToJSON,
    GroupReservationInputGroupReservationToJSONTyped,
} from './GroupReservationInputGroupReservation';

/**
 * 
 * @export
 * @interface GroupReservationInput
 */
export interface GroupReservationInput {
    /**
     * 
     * @type {GroupReservationInputGroupReservation}
     * @memberof GroupReservationInput
     */
    groupReservation: GroupReservationInputGroupReservation;
}

/**
 * Check if a given object implements the GroupReservationInput interface.
 */
export function instanceOfGroupReservationInput(value: object): value is GroupReservationInput {
    if (!('groupReservation' in value) || value['groupReservation'] === undefined) return false;
    return true;
}

export function GroupReservationInputFromJSON(json: any): GroupReservationInput {
    return GroupReservationInputFromJSONTyped(json, false);
}

export function GroupReservationInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupReservationInput {
    if (json == null) {
        return json;
    }
    return {
        
        'groupReservation': GroupReservationInputGroupReservationFromJSON(json['group_reservation']),
    };
}

export function GroupReservationInputToJSON(json: any): GroupReservationInput {
    return GroupReservationInputToJSONTyped(json, false);
}

export function GroupReservationInputToJSONTyped(value?: GroupReservationInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group_reservation': GroupReservationInputGroupReservationToJSON(value['groupReservation']),
    };
}

