/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Group
 */
export interface Group {
    /**
     * Unique identifier for the group
     * @type {number}
     * @memberof Group
     */
    id: number;
    /**
     * Name of the group (must be present)
     * @type {string}
     * @memberof Group
     */
    name: string;
    /**
     * Additional notes about this group
     * @type {string}
     * @memberof Group
     */
    notes?: string | null;
    /**
     * Whether this group applies across all sites in multi-site deployments
     * @type {boolean}
     * @memberof Group
     */
    globalAcrossSites: boolean;
    /**
     * Timestamp of creation
     * @type {Date}
     * @memberof Group
     */
    createdAt: Date;
    /**
     * Timestamp of last update
     * @type {Date}
     * @memberof Group
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the Group interface.
 */
export function instanceOfGroup(value: object): value is Group {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('globalAcrossSites' in value) || value['globalAcrossSites'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function GroupFromJSON(json: any): Group {
    return GroupFromJSONTyped(json, false);
}

export function GroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): Group {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'globalAcrossSites': json['global_across_sites'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function GroupToJSON(json: any): Group {
    return GroupToJSONTyped(json, false);
}

export function GroupToJSONTyped(value?: Group | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'notes': value['notes'],
        'global_across_sites': value['globalAcrossSites'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

