/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupReservationInputGroupReservation
 */
export interface GroupReservationInputGroupReservation {
    /**
     * ID of the person to assign to groups (must belong to the same account)
     * @type {number}
     * @memberof GroupReservationInputGroupReservation
     */
    personId: number;
    /**
     * Start time of the group reservation
     * @type {Date}
     * @memberof GroupReservationInputGroupReservation
     */
    startTime: Date;
    /**
     * End time of the group reservation (must be after start time and in the future)
     * @type {Date}
     * @memberof GroupReservationInputGroupReservation
     */
    endTime: Date;
    /**
     * Array of group IDs to assign the person to (at least one required, all must belong to the account)
     * @type {Array<number>}
     * @memberof GroupReservationInputGroupReservation
     */
    groupIds: Array<number>;
}

/**
 * Check if a given object implements the GroupReservationInputGroupReservation interface.
 */
export function instanceOfGroupReservationInputGroupReservation(value: object): value is GroupReservationInputGroupReservation {
    if (!('personId' in value) || value['personId'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    if (!('groupIds' in value) || value['groupIds'] === undefined) return false;
    return true;
}

export function GroupReservationInputGroupReservationFromJSON(json: any): GroupReservationInputGroupReservation {
    return GroupReservationInputGroupReservationFromJSONTyped(json, false);
}

export function GroupReservationInputGroupReservationFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupReservationInputGroupReservation {
    if (json == null) {
        return json;
    }
    return {
        
        'personId': json['person_id'],
        'startTime': (new Date(json['start_time'])),
        'endTime': (new Date(json['end_time'])),
        'groupIds': json['group_ids'],
    };
}

export function GroupReservationInputGroupReservationToJSON(json: any): GroupReservationInputGroupReservation {
    return GroupReservationInputGroupReservationToJSONTyped(json, false);
}

export function GroupReservationInputGroupReservationToJSONTyped(value?: GroupReservationInputGroupReservation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'person_id': value['personId'],
        'start_time': value['startTime'].toISOString(),
        'end_time': value['endTime'].toISOString(),
        'group_ids': value['groupIds'],
    };
}

