/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupReservation
 */
export interface GroupReservation {
    /**
     * Unique identifier for the group reservation
     * @type {number}
     * @memberof GroupReservation
     */
    id: number;
    /**
     * ID of the person assigned to the groups
     * @type {number}
     * @memberof GroupReservation
     */
    personId: number;
    /**
     * Start time of the group reservation
     * @type {Date}
     * @memberof GroupReservation
     */
    startTime: Date;
    /**
     * End time of the group reservation (must be after start time and in the future)
     * @type {Date}
     * @memberof GroupReservation
     */
    endTime: Date;
    /**
     * Current state of the reservation (pending = not started, active = in progress, deactivated = cancelled or completed)
     * @type {string}
     * @memberof GroupReservation
     */
    state: GroupReservationStateEnum;
    /**
     * Array of group IDs the person is assigned to during this reservation
     * @type {Array<number>}
     * @memberof GroupReservation
     */
    groupIds: Array<number>;
    /**
     * Timestamp of creation
     * @type {Date}
     * @memberof GroupReservation
     */
    createdAt: Date;
    /**
     * Timestamp of last update
     * @type {Date}
     * @memberof GroupReservation
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const GroupReservationStateEnum = {
    Pending: 'pending',
    Active: 'active',
    Deactivated: 'deactivated'
} as const;
export type GroupReservationStateEnum = typeof GroupReservationStateEnum[keyof typeof GroupReservationStateEnum];


/**
 * Check if a given object implements the GroupReservation interface.
 */
export function instanceOfGroupReservation(value: object): value is GroupReservation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('personId' in value) || value['personId'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('groupIds' in value) || value['groupIds'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function GroupReservationFromJSON(json: any): GroupReservation {
    return GroupReservationFromJSONTyped(json, false);
}

export function GroupReservationFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupReservation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'personId': json['person_id'],
        'startTime': (new Date(json['start_time'])),
        'endTime': (new Date(json['end_time'])),
        'state': json['state'],
        'groupIds': json['group_ids'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function GroupReservationToJSON(json: any): GroupReservation {
    return GroupReservationToJSONTyped(json, false);
}

export function GroupReservationToJSONTyped(value?: GroupReservation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'person_id': value['personId'],
        'start_time': value['startTime'].toISOString(),
        'end_time': value['endTime'].toISOString(),
        'state': value['state'],
        'group_ids': value['groupIds'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

