/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * LDAP Endpoint
 * @export
 * @interface LDAPEndpoint
 */
export interface LDAPEndpoint {
    /**
     * 
     * @type {number}
     * @memberof LDAPEndpoint
     */
    accountId?: number;
    /**
     * 
     * @type {string}
     * @memberof LDAPEndpoint
     */
    endpointLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof LDAPEndpoint
     */
    endpointHost?: string;
    /**
     * 
     * @type {number}
     * @memberof LDAPEndpoint
     */
    endpointPort?: number;
    /**
     * 
     * @type {string}
     * @memberof LDAPEndpoint
     */
    endpointMethod?: string;
    /**
     * 
     * @type {string}
     * @memberof LDAPEndpoint
     */
    endpointKey?: string;
}

/**
 * Check if a given object implements the LDAPEndpoint interface.
 */
export function instanceOfLDAPEndpoint(value: object): value is LDAPEndpoint {
    return true;
}

export function LDAPEndpointFromJSON(json: any): LDAPEndpoint {
    return LDAPEndpointFromJSONTyped(json, false);
}

export function LDAPEndpointFromJSONTyped(json: any, ignoreDiscriminator: boolean): LDAPEndpoint {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'endpointLabel': json['endpoint_label'] == null ? undefined : json['endpoint_label'],
        'endpointHost': json['endpoint_host'] == null ? undefined : json['endpoint_host'],
        'endpointPort': json['endpoint_port'] == null ? undefined : json['endpoint_port'],
        'endpointMethod': json['endpoint_method'] == null ? undefined : json['endpoint_method'],
        'endpointKey': json['endpoint_key'] == null ? undefined : json['endpoint_key'],
    };
}

export function LDAPEndpointToJSON(json: any): LDAPEndpoint {
    return LDAPEndpointToJSONTyped(json, false);
}

export function LDAPEndpointToJSONTyped(value?: LDAPEndpoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_id': value['accountId'],
        'endpoint_label': value['endpointLabel'],
        'endpoint_host': value['endpointHost'],
        'endpoint_port': value['endpointPort'],
        'endpoint_method': value['endpointMethod'],
        'endpoint_key': value['endpointKey'],
    };
}

