/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListEvents400Response
 */
export interface ListEvents400Response {
    /**
     * 
     * @type {string}
     * @memberof ListEvents400Response
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof ListEvents400Response
     */
    errorDescription?: string;
}

/**
 * Check if a given object implements the ListEvents400Response interface.
 */
export function instanceOfListEvents400Response(value: object): value is ListEvents400Response {
    return true;
}

export function ListEvents400ResponseFromJSON(json: any): ListEvents400Response {
    return ListEvents400ResponseFromJSONTyped(json, false);
}

export function ListEvents400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEvents400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'errorDescription': json['error_description'] == null ? undefined : json['error_description'],
    };
}

export function ListEvents400ResponseToJSON(json: any): ListEvents400Response {
    return ListEvents400ResponseToJSONTyped(json, false);
}

export function ListEvents400ResponseToJSONTyped(value?: ListEvents400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'error_description': value['errorDescription'],
    };
}

