/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LockdownChannelRequest
 */
export interface LockdownChannelRequest {
    /**
     * Lock down card access
     * @type {boolean}
     * @memberof LockdownChannelRequest
     */
    cardLockdown?: boolean;
    /**
     * Lock down REX (Request to Exit)
     * @type {boolean}
     * @memberof LockdownChannelRequest
     */
    rexLockdown?: boolean;
    /**
     * Lock down AUX inputs
     * @type {boolean}
     * @memberof LockdownChannelRequest
     */
    auxLockdown?: boolean;
}

/**
 * Check if a given object implements the LockdownChannelRequest interface.
 */
export function instanceOfLockdownChannelRequest(value: object): value is LockdownChannelRequest {
    return true;
}

export function LockdownChannelRequestFromJSON(json: any): LockdownChannelRequest {
    return LockdownChannelRequestFromJSONTyped(json, false);
}

export function LockdownChannelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LockdownChannelRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'cardLockdown': json['card_lockdown'] == null ? undefined : json['card_lockdown'],
        'rexLockdown': json['rex_lockdown'] == null ? undefined : json['rex_lockdown'],
        'auxLockdown': json['aux_lockdown'] == null ? undefined : json['aux_lockdown'],
    };
}

export function LockdownChannelRequestToJSON(json: any): LockdownChannelRequest {
    return LockdownChannelRequestToJSONTyped(json, false);
}

export function LockdownChannelRequestToJSONTyped(value?: LockdownChannelRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'card_lockdown': value['cardLockdown'],
        'rex_lockdown': value['rexLockdown'],
        'aux_lockdown': value['auxLockdown'],
    };
}

