/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationRuleEventsInner } from './NotificationRuleEventsInner';
import {
    NotificationRuleEventsInnerFromJSON,
    NotificationRuleEventsInnerFromJSONTyped,
    NotificationRuleEventsInnerToJSON,
    NotificationRuleEventsInnerToJSONTyped,
} from './NotificationRuleEventsInner';
import type { NotificationRuleActionsInner } from './NotificationRuleActionsInner';
import {
    NotificationRuleActionsInnerFromJSON,
    NotificationRuleActionsInnerFromJSONTyped,
    NotificationRuleActionsInnerToJSON,
    NotificationRuleActionsInnerToJSONTyped,
} from './NotificationRuleActionsInner';
import type { NotificationRuleConditionsInner } from './NotificationRuleConditionsInner';
import {
    NotificationRuleConditionsInnerFromJSON,
    NotificationRuleConditionsInnerFromJSONTyped,
    NotificationRuleConditionsInnerToJSON,
    NotificationRuleConditionsInnerToJSONTyped,
} from './NotificationRuleConditionsInner';

/**
 * 
 * @export
 * @interface NotificationRule
 */
export interface NotificationRule {
    /**
     * Unique identifier for the notification rule
     * @type {number}
     * @memberof NotificationRule
     */
    id: number;
    /**
     * Name of the notification rule
     * @type {string}
     * @memberof NotificationRule
     */
    name: string;
    /**
     * Whether this notification rule is currently active
     * @type {boolean}
     * @memberof NotificationRule
     */
    active: boolean;
    /**
     * Conditions that must be met for the rule to trigger
     * @type {Array<NotificationRuleConditionsInner>}
     * @memberof NotificationRule
     */
    conditions: Array<NotificationRuleConditionsInner>;
    /**
     * Events that trigger this rule (at least one required)
     * @type {Array<NotificationRuleEventsInner>}
     * @memberof NotificationRule
     */
    events: Array<NotificationRuleEventsInner>;
    /**
     * Actions to perform when the rule triggers (at least one required)
     * @type {Array<NotificationRuleActionsInner>}
     * @memberof NotificationRule
     */
    actions: Array<NotificationRuleActionsInner>;
}

/**
 * Check if a given object implements the NotificationRule interface.
 */
export function instanceOfNotificationRule(value: object): value is NotificationRule {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('conditions' in value) || value['conditions'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    if (!('actions' in value) || value['actions'] === undefined) return false;
    return true;
}

export function NotificationRuleFromJSON(json: any): NotificationRule {
    return NotificationRuleFromJSONTyped(json, false);
}

export function NotificationRuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationRule {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'active': json['active'],
        'conditions': ((json['conditions'] as Array<any>).map(NotificationRuleConditionsInnerFromJSON)),
        'events': ((json['events'] as Array<any>).map(NotificationRuleEventsInnerFromJSON)),
        'actions': ((json['actions'] as Array<any>).map(NotificationRuleActionsInnerFromJSON)),
    };
}

export function NotificationRuleToJSON(json: any): NotificationRule {
    return NotificationRuleToJSONTyped(json, false);
}

export function NotificationRuleToJSONTyped(value?: NotificationRule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'active': value['active'],
        'conditions': ((value['conditions'] as Array<any>).map(NotificationRuleConditionsInnerToJSON)),
        'events': ((value['events'] as Array<any>).map(NotificationRuleEventsInnerToJSON)),
        'actions': ((value['actions'] as Array<any>).map(NotificationRuleActionsInnerToJSON)),
    };
}

