/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationRuleActionsInner
 */
export interface NotificationRuleActionsInner {
    /**
     * Type of action (0 = webhook callback)
     * @type {number}
     * @memberof NotificationRuleActionsInner
     */
    type?: number;
    /**
     * Human-readable description of the action type
     * @type {string}
     * @memberof NotificationRuleActionsInner
     */
    typeDescription?: string;
    /**
     * Action data (e.g., webhook URL)
     * @type {string}
     * @memberof NotificationRuleActionsInner
     */
    data?: string;
}

/**
 * Check if a given object implements the NotificationRuleActionsInner interface.
 */
export function instanceOfNotificationRuleActionsInner(value: object): value is NotificationRuleActionsInner {
    return true;
}

export function NotificationRuleActionsInnerFromJSON(json: any): NotificationRuleActionsInner {
    return NotificationRuleActionsInnerFromJSONTyped(json, false);
}

export function NotificationRuleActionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationRuleActionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'typeDescription': json['type_description'] == null ? undefined : json['type_description'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function NotificationRuleActionsInnerToJSON(json: any): NotificationRuleActionsInner {
    return NotificationRuleActionsInnerToJSONTyped(json, false);
}

export function NotificationRuleActionsInnerToJSONTyped(value?: NotificationRuleActionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'type_description': value['typeDescription'],
        'data': value['data'],
    };
}

