/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationRuleEventsInner
 */
export interface NotificationRuleEventsInner {
    /**
     * Event code that triggers this rule
     * @type {number}
     * @memberof NotificationRuleEventsInner
     */
    code?: number;
    /**
     * Human-readable name of the event
     * @type {string}
     * @memberof NotificationRuleEventsInner
     */
    name?: string;
}

/**
 * Check if a given object implements the NotificationRuleEventsInner interface.
 */
export function instanceOfNotificationRuleEventsInner(value: object): value is NotificationRuleEventsInner {
    return true;
}

export function NotificationRuleEventsInnerFromJSON(json: any): NotificationRuleEventsInner {
    return NotificationRuleEventsInnerFromJSONTyped(json, false);
}

export function NotificationRuleEventsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationRuleEventsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function NotificationRuleEventsInnerToJSON(json: any): NotificationRuleEventsInner {
    return NotificationRuleEventsInnerToJSONTyped(json, false);
}

export function NotificationRuleEventsInnerToJSONTyped(value?: NotificationRuleEventsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'name': value['name'],
    };
}

