/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationRuleConditionsInner
 */
export interface NotificationRuleConditionsInner {
    /**
     * Type of condition (e.g., "door_controller_id")
     * @type {string}
     * @memberof NotificationRuleConditionsInner
     */
    type?: string;
    /**
     * Human-readable description of the condition type
     * @type {string}
     * @memberof NotificationRuleConditionsInner
     */
    typeDescription?: string;
    /**
     * Value to match against
     * @type {string}
     * @memberof NotificationRuleConditionsInner
     */
    value?: string;
}

/**
 * Check if a given object implements the NotificationRuleConditionsInner interface.
 */
export function instanceOfNotificationRuleConditionsInner(value: object): value is NotificationRuleConditionsInner {
    return true;
}

export function NotificationRuleConditionsInnerFromJSON(json: any): NotificationRuleConditionsInner {
    return NotificationRuleConditionsInnerFromJSONTyped(json, false);
}

export function NotificationRuleConditionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationRuleConditionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'typeDescription': json['type_description'] == null ? undefined : json['type_description'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function NotificationRuleConditionsInnerToJSON(json: any): NotificationRuleConditionsInner {
    return NotificationRuleConditionsInnerToJSONTyped(json, false);
}

export function NotificationRuleConditionsInnerToJSONTyped(value?: NotificationRuleConditionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'type_description': value['typeDescription'],
        'value': value['value'],
    };
}

