/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationRuleInput
 */
export interface NotificationRuleInput {
    /**
     * Name of the notification rule (required)
     * @type {string}
     * @memberof NotificationRuleInput
     */
    name: string;
    /**
     * Whether this notification rule is active
     * @type {boolean}
     * @memberof NotificationRuleInput
     */
    active?: boolean;
    /**
     * Webhook callback URL to trigger when events occur (required)
     * @type {string}
     * @memberof NotificationRuleInput
     */
    callBackUrl: string;
    /**
     * Array of event codes that trigger this rule (at least one required)
     * @type {Array<number>}
     * @memberof NotificationRuleInput
     */
    matchEventCodes: Array<number>;
    /**
     * Array of door controller IDs to filter events (optional - if omitted, matches all controllers)
     * @type {Array<number>}
     * @memberof NotificationRuleInput
     */
    matchControllerIds?: Array<number>;
}

/**
 * Check if a given object implements the NotificationRuleInput interface.
 */
export function instanceOfNotificationRuleInput(value: object): value is NotificationRuleInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('callBackUrl' in value) || value['callBackUrl'] === undefined) return false;
    if (!('matchEventCodes' in value) || value['matchEventCodes'] === undefined) return false;
    return true;
}

export function NotificationRuleInputFromJSON(json: any): NotificationRuleInput {
    return NotificationRuleInputFromJSONTyped(json, false);
}

export function NotificationRuleInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationRuleInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'active': json['active'] == null ? undefined : json['active'],
        'callBackUrl': json['call_back_url'],
        'matchEventCodes': json['match_event_codes'],
        'matchControllerIds': json['match_controller_ids'] == null ? undefined : json['match_controller_ids'],
    };
}

export function NotificationRuleInputToJSON(json: any): NotificationRuleInput {
    return NotificationRuleInputToJSONTyped(json, false);
}

export function NotificationRuleInputToJSONTyped(value?: NotificationRuleInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'active': value['active'],
        'call_back_url': value['callBackUrl'],
        'match_event_codes': value['matchEventCodes'],
        'match_controller_ids': value['matchControllerIds'],
    };
}

