/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Person
 */
export interface Person {
    [key: string]: any | any;
    /**
     * Unique identifier for the person
     * @type {number}
     * @memberof Person
     */
    id: number;
    /**
     * First name (required)
     * @type {string}
     * @memberof Person
     */
    firstName: string;
    /**
     * Last name (required)
     * @type {string}
     * @memberof Person
     */
    lastName: string;
    /**
     * Salutation or title (Mr., Ms., Dr., etc.)
     * @type {string}
     * @memberof Person
     */
    salutation?: string | null;
    /**
     * Job title
     * @type {string}
     * @memberof Person
     */
    jobTitle?: string | null;
    /**
     * Email address (must be unique within account if provided)
     * @type {string}
     * @memberof Person
     */
    email?: string | null;
    /**
     * Organisation ID
     * @type {number}
     * @memberof Person
     */
    organisationId?: number | null;
    /**
     * External system identifier
     * @type {string}
     * @memberof Person
     */
    systemId?: string | null;
    /**
     * Department name
     * @type {string}
     * @memberof Person
     */
    department?: string | null;
    /**
     * Whether the person is currently enabled for access
     * @type {boolean}
     * @memberof Person
     */
    enabled: boolean;
    /**
     * Access valid from this date/time
     * @type {Date}
     * @memberof Person
     */
    validFrom?: Date | null;
    /**
     * Access valid until this date/time
     * @type {Date}
     * @memberof Person
     */
    validTo?: Date | null;
    /**
     * URL to person's full-size photo
     * @type {string}
     * @memberof Person
     */
    imageUrl?: string | null;
    /**
     * URL to person's thumbnail photo
     * @type {string}
     * @memberof Person
     */
    imageThumbnailUrl?: string | null;
    /**
     * Telephone number
     * @type {string}
     * @memberof Person
     */
    telephone?: string | null;
    /**
     * Mobile number (E.164 format required if passport enabled)
     * @type {string}
     * @memberof Person
     */
    mobile?: string | null;
    /**
     * Additional notes
     * @type {string}
     * @memberof Person
     */
    notes?: string | null;
    /**
     * Barcode identifier
     * @type {string}
     * @memberof Person
     */
    barcode?: string | null;
    /**
     * Custom field 1
     * @type {string}
     * @memberof Person
     */
    custom1?: string | null;
    /**
     * Custom field 2
     * @type {string}
     * @memberof Person
     */
    custom2?: string | null;
    /**
     * Custom field 3
     * @type {string}
     * @memberof Person
     */
    custom3?: string | null;
    /**
     * Custom field 4
     * @type {string}
     * @memberof Person
     */
    custom4?: string | null;
    /**
     * Custom field 5
     * @type {string}
     * @memberof Person
     */
    custom5?: string | null;
    /**
     * Timestamp of creation
     * @type {Date}
     * @memberof Person
     */
    createdAt?: Date;
    /**
     * Timestamp of last update
     * @type {Date}
     * @memberof Person
     */
    updatedAt?: Date;
    /**
     * Array of group IDs this person belongs to
     * @type {Array<number>}
     * @memberof Person
     */
    groups: Array<number>;
    /**
     * Array of role IDs assigned to this person
     * @type {Array<number>}
     * @memberof Person
     */
    roles: Array<number>;
}

/**
 * Check if a given object implements the Person interface.
 */
export function instanceOfPerson(value: object): value is Person {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('groups' in value) || value['groups'] === undefined) return false;
    if (!('roles' in value) || value['roles'] === undefined) return false;
    return true;
}

export function PersonFromJSON(json: any): Person {
    return PersonFromJSONTyped(json, false);
}

export function PersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): Person {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'salutation': json['salutation'] == null ? undefined : json['salutation'],
        'jobTitle': json['job_title'] == null ? undefined : json['job_title'],
        'email': json['email'] == null ? undefined : json['email'],
        'organisationId': json['organisation_id'] == null ? undefined : json['organisation_id'],
        'systemId': json['system_id'] == null ? undefined : json['system_id'],
        'department': json['department'] == null ? undefined : json['department'],
        'enabled': json['enabled'],
        'validFrom': json['valid_from'] == null ? undefined : (new Date(json['valid_from'])),
        'validTo': json['valid_to'] == null ? undefined : (new Date(json['valid_to'])),
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'imageThumbnailUrl': json['image_thumbnail_url'] == null ? undefined : json['image_thumbnail_url'],
        'telephone': json['telephone'] == null ? undefined : json['telephone'],
        'mobile': json['mobile'] == null ? undefined : json['mobile'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'barcode': json['barcode'] == null ? undefined : json['barcode'],
        'custom1': json['custom_1'] == null ? undefined : json['custom_1'],
        'custom2': json['custom_2'] == null ? undefined : json['custom_2'],
        'custom3': json['custom_3'] == null ? undefined : json['custom_3'],
        'custom4': json['custom_4'] == null ? undefined : json['custom_4'],
        'custom5': json['custom_5'] == null ? undefined : json['custom_5'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'groups': json['groups'],
        'roles': json['roles'],
    };
}

export function PersonToJSON(json: any): Person {
    return PersonToJSONTyped(json, false);
}

export function PersonToJSONTyped(value?: Person | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'salutation': value['salutation'],
        'job_title': value['jobTitle'],
        'email': value['email'],
        'organisation_id': value['organisationId'],
        'system_id': value['systemId'],
        'department': value['department'],
        'enabled': value['enabled'],
        'valid_from': value['validFrom'] == null ? value['validFrom'] : value['validFrom'].toISOString(),
        'valid_to': value['validTo'] == null ? value['validTo'] : value['validTo'].toISOString(),
        'image_url': value['imageUrl'],
        'image_thumbnail_url': value['imageThumbnailUrl'],
        'telephone': value['telephone'],
        'mobile': value['mobile'],
        'notes': value['notes'],
        'barcode': value['barcode'],
        'custom_1': value['custom1'],
        'custom_2': value['custom2'],
        'custom_3': value['custom3'],
        'custom_4': value['custom4'],
        'custom_5': value['custom5'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'groups': value['groups'],
        'roles': value['roles'],
    };
}

