/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Role } from './Role';
import {
    RoleFromJSON,
    RoleFromJSONTyped,
    RoleToJSON,
    RoleToJSONTyped,
} from './Role';
import type { Group } from './Group';
import {
    GroupFromJSON,
    GroupFromJSONTyped,
    GroupToJSON,
    GroupToJSONTyped,
} from './Group';

/**
 * 
 * @export
 * @interface Person
 */
export interface Person {
    /**
     * 
     * @type {number}
     * @memberof Person
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof Person
     */
    accountId: number;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    salutation?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    jobTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    organisationId?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    systemId: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    department?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Person
     */
    enabled: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Person
     */
    validFrom?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Person
     */
    validTo?: Date;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    credentialsNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    keyFobNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    pin?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    magstripeCardIdentifier?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    imageThumbnailUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    telephone?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    mobile?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    barcode?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    custom1?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    custom2?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    custom3?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    custom4?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    custom5?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    passportToken?: string;
    /**
     * 
     * @type {Set<Group>}
     * @memberof Person
     */
    groups: Set<Group>;
    /**
     * 
     * @type {Array<Role>}
     * @memberof Person
     */
    roles: Array<Role>;
}

/**
 * Check if a given object implements the Person interface.
 */
export function instanceOfPerson(value: object): value is Person {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('systemId' in value) || value['systemId'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('groups' in value) || value['groups'] === undefined) return false;
    if (!('roles' in value) || value['roles'] === undefined) return false;
    return true;
}

export function PersonFromJSON(json: any): Person {
    return PersonFromJSONTyped(json, false);
}

export function PersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): Person {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'accountId': json['account_id'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'salutation': json['salutation'] == null ? undefined : json['salutation'],
        'jobTitle': json['job_title'] == null ? undefined : json['job_title'],
        'email': json['email'],
        'organisationId': json['organisation_id'] == null ? undefined : json['organisation_id'],
        'systemId': json['system_id'],
        'department': json['department'] == null ? undefined : json['department'],
        'enabled': json['enabled'],
        'validFrom': json['valid_from'] == null ? undefined : (new Date(json['valid_from'])),
        'validTo': json['valid_to'] == null ? undefined : (new Date(json['valid_to'])),
        'credentialsNumber': json['credentials_number'] == null ? undefined : json['credentials_number'],
        'keyFobNumber': json['key_fob_number'] == null ? undefined : json['key_fob_number'],
        'pin': json['pin'] == null ? undefined : json['pin'],
        'magstripeCardIdentifier': json['magstripe_card_identifier'] == null ? undefined : json['magstripe_card_identifier'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'imageThumbnailUrl': json['image_thumbnail_url'] == null ? undefined : json['image_thumbnail_url'],
        'telephone': json['telephone'] == null ? undefined : json['telephone'],
        'mobile': json['mobile'] == null ? undefined : json['mobile'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'barcode': json['barcode'] == null ? undefined : json['barcode'],
        'custom1': json['custom_1'] == null ? undefined : json['custom_1'],
        'custom2': json['custom_2'] == null ? undefined : json['custom_2'],
        'custom3': json['custom_3'] == null ? undefined : json['custom_3'],
        'custom4': json['custom_4'] == null ? undefined : json['custom_4'],
        'custom5': json['custom_5'] == null ? undefined : json['custom_5'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'passportToken': json['passport_token'] == null ? undefined : json['passport_token'],
        'groups': (new Set((json['groups'] as Array<any>).map(GroupFromJSON))),
        'roles': ((json['roles'] as Array<any>).map(RoleFromJSON)),
    };
}

export function PersonToJSON(json: any): Person {
    return PersonToJSONTyped(json, false);
}

export function PersonToJSONTyped(value?: Person | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'account_id': value['accountId'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'salutation': value['salutation'],
        'job_title': value['jobTitle'],
        'email': value['email'],
        'organisation_id': value['organisationId'],
        'system_id': value['systemId'],
        'department': value['department'],
        'enabled': value['enabled'],
        'valid_from': value['validFrom'] == null ? undefined : ((value['validFrom']).toISOString()),
        'valid_to': value['validTo'] == null ? undefined : ((value['validTo']).toISOString()),
        'credentials_number': value['credentialsNumber'],
        'key_fob_number': value['keyFobNumber'],
        'pin': value['pin'],
        'magstripe_card_identifier': value['magstripeCardIdentifier'],
        'image_url': value['imageUrl'],
        'image_thumbnail_url': value['imageThumbnailUrl'],
        'telephone': value['telephone'],
        'mobile': value['mobile'],
        'notes': value['notes'],
        'barcode': value['barcode'],
        'custom_1': value['custom1'],
        'custom_2': value['custom2'],
        'custom_3': value['custom3'],
        'custom_4': value['custom4'],
        'custom_5': value['custom5'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
        'passport_token': value['passportToken'],
        'groups': (Array.from(value['groups'] as Set<any>).map(GroupToJSON)),
        'roles': ((value['roles'] as Array<any>).map(RoleToJSON)),
    };
}

