/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PersonInput
 */
export interface PersonInput {
    [key: string]: any | any;
    /**
     * First name (required for creation)
     * @type {string}
     * @memberof PersonInput
     */
    firstName?: string;
    /**
     * Last name (required for creation)
     * @type {string}
     * @memberof PersonInput
     */
    lastName?: string;
    /**
     * Salutation or title
     * @type {string}
     * @memberof PersonInput
     */
    salutation?: string | null;
    /**
     * Job title
     * @type {string}
     * @memberof PersonInput
     */
    jobTitle?: string | null;
    /**
     * Email address (must be unique within account if provided)
     * @type {string}
     * @memberof PersonInput
     */
    email?: string | null;
    /**
     * Department name
     * @type {string}
     * @memberof PersonInput
     */
    department?: string | null;
    /**
     * Whether the person is enabled for access
     * @type {boolean}
     * @memberof PersonInput
     */
    enabled?: boolean;
    /**
     * Access valid from this date/time
     * @type {Date}
     * @memberof PersonInput
     */
    validFrom?: Date | null;
    /**
     * Access valid until this date/time
     * @type {Date}
     * @memberof PersonInput
     */
    validTo?: Date | null;
    /**
     * Base64-encoded image data for person's photo
     * @type {string}
     * @memberof PersonInput
     */
    imageBase64?: string | null;
    /**
     * Remote URL to fetch person's photo from (set to empty string to delete image)
     * @type {string}
     * @memberof PersonInput
     */
    imageRemoteUrl?: string | null;
    /**
     * Telephone number
     * @type {string}
     * @memberof PersonInput
     */
    telephone?: string | null;
    /**
     * Mobile number (E.164 format if passport enabled)
     * @type {string}
     * @memberof PersonInput
     */
    mobile?: string | null;
    /**
     * Additional notes
     * @type {string}
     * @memberof PersonInput
     */
    notes?: string | null;
    /**
     * Barcode identifier
     * @type {string}
     * @memberof PersonInput
     */
    barcode?: string | null;
    /**
     * External system identifier
     * @type {string}
     * @memberof PersonInput
     */
    systemId?: string | null;
    /**
     * Organisation ID
     * @type {number}
     * @memberof PersonInput
     */
    organisationId?: number | null;
    /**
     * Custom field 1
     * @type {string}
     * @memberof PersonInput
     */
    custom1?: string | null;
    /**
     * Custom field 2
     * @type {string}
     * @memberof PersonInput
     */
    custom2?: string | null;
    /**
     * Custom field 3
     * @type {string}
     * @memberof PersonInput
     */
    custom3?: string | null;
    /**
     * Custom field 4
     * @type {string}
     * @memberof PersonInput
     */
    custom4?: string | null;
    /**
     * Custom field 5
     * @type {string}
     * @memberof PersonInput
     */
    custom5?: string | null;
    /**
     * Array of group IDs to assign this person to
     * @type {Array<number>}
     * @memberof PersonInput
     */
    groupIds?: Array<number>;
    /**
     * Array of role IDs to assign to this person (requires permission)
     * @type {Array<number>}
     * @memberof PersonInput
     */
    roleIds?: Array<number>;
    /**
     * Mark person as deleted (used internally)
     * @type {boolean}
     * @memberof PersonInput
     */
    deleted?: boolean;
}

/**
 * Check if a given object implements the PersonInput interface.
 */
export function instanceOfPersonInput(value: object): value is PersonInput {
    return true;
}

export function PersonInputFromJSON(json: any): PersonInput {
    return PersonInputFromJSONTyped(json, false);
}

export function PersonInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonInput {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'salutation': json['salutation'] == null ? undefined : json['salutation'],
        'jobTitle': json['job_title'] == null ? undefined : json['job_title'],
        'email': json['email'] == null ? undefined : json['email'],
        'department': json['department'] == null ? undefined : json['department'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'validFrom': json['valid_from'] == null ? undefined : (new Date(json['valid_from'])),
        'validTo': json['valid_to'] == null ? undefined : (new Date(json['valid_to'])),
        'imageBase64': json['image_base64'] == null ? undefined : json['image_base64'],
        'imageRemoteUrl': json['image_remote_url'] == null ? undefined : json['image_remote_url'],
        'telephone': json['telephone'] == null ? undefined : json['telephone'],
        'mobile': json['mobile'] == null ? undefined : json['mobile'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'barcode': json['barcode'] == null ? undefined : json['barcode'],
        'systemId': json['system_id'] == null ? undefined : json['system_id'],
        'organisationId': json['organisation_id'] == null ? undefined : json['organisation_id'],
        'custom1': json['custom_1'] == null ? undefined : json['custom_1'],
        'custom2': json['custom_2'] == null ? undefined : json['custom_2'],
        'custom3': json['custom_3'] == null ? undefined : json['custom_3'],
        'custom4': json['custom_4'] == null ? undefined : json['custom_4'],
        'custom5': json['custom_5'] == null ? undefined : json['custom_5'],
        'groupIds': json['group_ids'] == null ? undefined : json['group_ids'],
        'roleIds': json['role_ids'] == null ? undefined : json['role_ids'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
    };
}

export function PersonInputToJSON(json: any): PersonInput {
    return PersonInputToJSONTyped(json, false);
}

export function PersonInputToJSONTyped(value?: PersonInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'salutation': value['salutation'],
        'job_title': value['jobTitle'],
        'email': value['email'],
        'department': value['department'],
        'enabled': value['enabled'],
        'valid_from': value['validFrom'] == null ? value['validFrom'] : value['validFrom'].toISOString(),
        'valid_to': value['validTo'] == null ? value['validTo'] : value['validTo'].toISOString(),
        'image_base64': value['imageBase64'],
        'image_remote_url': value['imageRemoteUrl'],
        'telephone': value['telephone'],
        'mobile': value['mobile'],
        'notes': value['notes'],
        'barcode': value['barcode'],
        'system_id': value['systemId'],
        'organisation_id': value['organisationId'],
        'custom_1': value['custom1'],
        'custom_2': value['custom2'],
        'custom_3': value['custom3'],
        'custom_4': value['custom4'],
        'custom_5': value['custom5'],
        'group_ids': value['groupIds'],
        'role_ids': value['roleIds'],
        'deleted': value['deleted'],
    };
}

