/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Reservation
 */
export interface Reservation {
    /**
     * Unique identifier for the reservation
     * @type {number}
     * @memberof Reservation
     */
    id: number;
    /**
     * ID of the person granted temporary access
     * @type {number}
     * @memberof Reservation
     */
    personId: number;
    /**
     * Start time of the reservation
     * @type {Date}
     * @memberof Reservation
     */
    startTime: Date;
    /**
     * End time of the reservation (must be after start time and on the same day)
     * @type {Date}
     * @memberof Reservation
     */
    endTime: Date;
    /**
     * Array of channel (door controller) IDs the person has access to during this reservation
     * @type {Array<number>}
     * @memberof Reservation
     */
    channelIds: Array<number>;
    /**
     * Timestamp of creation
     * @type {Date}
     * @memberof Reservation
     */
    createdAt: Date;
    /**
     * Timestamp of last update
     * @type {Date}
     * @memberof Reservation
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the Reservation interface.
 */
export function instanceOfReservation(value: object): value is Reservation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('personId' in value) || value['personId'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    if (!('channelIds' in value) || value['channelIds'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ReservationFromJSON(json: any): Reservation {
    return ReservationFromJSONTyped(json, false);
}

export function ReservationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Reservation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'personId': json['person_id'],
        'startTime': (new Date(json['start_time'])),
        'endTime': (new Date(json['end_time'])),
        'channelIds': json['channel_ids'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function ReservationToJSON(json: any): Reservation {
    return ReservationToJSONTyped(json, false);
}

export function ReservationToJSONTyped(value?: Reservation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'person_id': value['personId'],
        'start_time': value['startTime'].toISOString(),
        'end_time': value['endTime'].toISOString(),
        'channel_ids': value['channelIds'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

