/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReservationInput
 */
export interface ReservationInput {
    /**
     * ID of the person to grant temporary access (must belong to the same account)
     * @type {number}
     * @memberof ReservationInput
     */
    personId: number;
    /**
     * Start time of the reservation
     * @type {Date}
     * @memberof ReservationInput
     */
    startTime: Date;
    /**
     * End time of the reservation (must be after start time and on the same day in account time zone)
     * @type {Date}
     * @memberof ReservationInput
     */
    endTime: Date;
    /**
     * Array of channel IDs to grant access to (at least one required, all must be accessible to the creator)
     * @type {Array<number>}
     * @memberof ReservationInput
     */
    channelIds?: Array<number>;
    /**
     * Alias for channel_ids
     * @type {Array<number>}
     * @memberof ReservationInput
     */
    doorControllerIds?: Array<number>;
}

/**
 * Check if a given object implements the ReservationInput interface.
 */
export function instanceOfReservationInput(value: object): value is ReservationInput {
    if (!('personId' in value) || value['personId'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    return true;
}

export function ReservationInputFromJSON(json: any): ReservationInput {
    return ReservationInputFromJSONTyped(json, false);
}

export function ReservationInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationInput {
    if (json == null) {
        return json;
    }
    return {
        
        'personId': json['person_id'],
        'startTime': (new Date(json['start_time'])),
        'endTime': (new Date(json['end_time'])),
        'channelIds': json['channel_ids'] == null ? undefined : json['channel_ids'],
        'doorControllerIds': json['door_controller_ids'] == null ? undefined : json['door_controller_ids'],
    };
}

export function ReservationInputToJSON(json: any): ReservationInput {
    return ReservationInputToJSONTyped(json, false);
}

export function ReservationInputToJSONTyped(value?: ReservationInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'person_id': value['personId'],
        'start_time': value['startTime'].toISOString(),
        'end_time': value['endTime'].toISOString(),
        'channel_ids': value['channelIds'],
        'door_controller_ids': value['doorControllerIds'],
    };
}

