/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RevokeToken403Response
 */
export interface RevokeToken403Response {
    /**
     * 
     * @type {string}
     * @memberof RevokeToken403Response
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof RevokeToken403Response
     */
    errorDescription?: string;
}

/**
 * Check if a given object implements the RevokeToken403Response interface.
 */
export function instanceOfRevokeToken403Response(value: object): value is RevokeToken403Response {
    return true;
}

export function RevokeToken403ResponseFromJSON(json: any): RevokeToken403Response {
    return RevokeToken403ResponseFromJSONTyped(json, false);
}

export function RevokeToken403ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevokeToken403Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'errorDescription': json['error_description'] == null ? undefined : json['error_description'],
    };
}

export function RevokeToken403ResponseToJSON(json: any): RevokeToken403Response {
    return RevokeToken403ResponseToJSONTyped(json, false);
}

export function RevokeToken403ResponseToJSONTyped(value?: RevokeToken403Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'error_description': value['errorDescription'],
    };
}

