/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Role
 */
export interface Role {
    /**
     * Unique identifier for the role
     * @type {number}
     * @memberof Role
     */
    id: number;
    /**
     * Name of the role (must be unique within the account)
     * @type {string}
     * @memberof Role
     */
    name: string;
    /**
     * ID of the shift defining when this role grants access (null means 24/7 access)
     * @type {number}
     * @memberof Role
     */
    shiftId?: number | null;
    /**
     * Additional notes about this role
     * @type {string}
     * @memberof Role
     */
    notes?: string | null;
    /**
     * Timestamp of creation
     * @type {Date}
     * @memberof Role
     */
    createdAt: Date;
    /**
     * Timestamp of last update
     * @type {Date}
     * @memberof Role
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the Role interface.
 */
export function instanceOfRole(value: object): value is Role {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function RoleFromJSON(json: any): Role {
    return RoleFromJSONTyped(json, false);
}

export function RoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Role {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'shiftId': json['shift_id'] == null ? undefined : json['shift_id'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function RoleToJSON(json: any): Role {
    return RoleToJSONTyped(json, false);
}

export function RoleToJSONTyped(value?: Role | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'shift_id': value['shiftId'],
        'notes': value['notes'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

