/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShiftTime
 */
export interface ShiftTime {
    /**
     * 
     * @type {string}
     * @memberof ShiftTime
     */
    day: ShiftTimeDayEnum;
    /**
     * 
     * @type {string}
     * @memberof ShiftTime
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ShiftTime
     */
    startTime: string;
    /**
     * 
     * @type {string}
     * @memberof ShiftTime
     */
    endTime: string;
}


/**
 * @export
 */
export const ShiftTimeDayEnum = {
    Sunday: 'Sunday',
    Monday: 'Monday',
    Tuesday: 'Tuesday',
    Wednesday: 'Wednesday',
    Thursday: 'Thursday',
    Friday: 'Friday',
    Saturday: 'Saturday'
} as const;
export type ShiftTimeDayEnum = typeof ShiftTimeDayEnum[keyof typeof ShiftTimeDayEnum];


/**
 * Check if a given object implements the ShiftTime interface.
 */
export function instanceOfShiftTime(value: object): value is ShiftTime {
    if (!('day' in value) || value['day'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    return true;
}

export function ShiftTimeFromJSON(json: any): ShiftTime {
    return ShiftTimeFromJSONTyped(json, false);
}

export function ShiftTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShiftTime {
    if (json == null) {
        return json;
    }
    return {
        
        'day': json['day'],
        'description': json['description'],
        'startTime': json['start_time'],
        'endTime': json['end_time'],
    };
}

export function ShiftTimeToJSON(json: any): ShiftTime {
    return ShiftTimeToJSONTyped(json, false);
}

export function ShiftTimeToJSONTyped(value?: ShiftTime | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'day': value['day'],
        'description': value['description'],
        'start_time': value['startTime'],
        'end_time': value['endTime'],
    };
}

