/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShiftTime } from './ShiftTime';
import {
    ShiftTimeFromJSON,
    ShiftTimeFromJSONTyped,
    ShiftTimeToJSON,
    ShiftTimeToJSONTyped,
} from './ShiftTime';

/**
 * 
 * @export
 * @interface Shift
 */
export interface Shift {
    /**
     * 
     * @type {number}
     * @memberof Shift
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Shift
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof Shift
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Shift
     */
    createdAt: Date;
    /**
     * 
     * @type {Set<ShiftTime>}
     * @memberof Shift
     */
    times: Set<ShiftTime>;
}

/**
 * Check if a given object implements the Shift interface.
 */
export function instanceOfShift(value: object): value is Shift {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('times' in value) || value['times'] === undefined) return false;
    return true;
}

export function ShiftFromJSON(json: any): Shift {
    return ShiftFromJSONTyped(json, false);
}

export function ShiftFromJSONTyped(json: any, ignoreDiscriminator: boolean): Shift {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'updatedAt': (new Date(json['updated_at'])),
        'createdAt': (new Date(json['created_at'])),
        'times': (new Set((json['times'] as Array<any>).map(ShiftTimeFromJSON))),
    };
}

export function ShiftToJSON(json: any): Shift {
    return ShiftToJSONTyped(json, false);
}

export function ShiftToJSONTyped(value?: Shift | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'updated_at': ((value['updatedAt']).toISOString()),
        'created_at': ((value['createdAt']).toISOString()),
        'times': (Array.from(value['times'] as Set<any>).map(ShiftTimeToJSON)),
    };
}

