/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SiteSiteIpsInner } from './SiteSiteIpsInner';
import {
    SiteSiteIpsInnerFromJSON,
    SiteSiteIpsInnerFromJSONTyped,
    SiteSiteIpsInnerToJSON,
    SiteSiteIpsInnerToJSONTyped,
} from './SiteSiteIpsInner';

/**
 * 
 * @export
 * @interface Site
 */
export interface Site {
    /**
     * Unique identifier for the site
     * @type {number}
     * @memberof Site
     */
    id: number;
    /**
     * Name of the site (required)
     * @type {string}
     * @memberof Site
     */
    name: string;
    /**
     * Primary IP address for the site (deprecated - use site_ips instead)
     * @type {string}
     * @memberof Site
     */
    ipAddress?: string | null;
    /**
     * IANA time zone identifier for this site
     * @type {string}
     * @memberof Site
     */
    timeZone?: string | null;
    /**
     * Additional notes about this site
     * @type {string}
     * @memberof Site
     */
    notes?: string | null;
    /**
     * Array of IP address ranges associated with this site
     * @type {Array<SiteSiteIpsInner>}
     * @memberof Site
     */
    siteIps: Array<SiteSiteIpsInner>;
}

/**
 * Check if a given object implements the Site interface.
 */
export function instanceOfSite(value: object): value is Site {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('siteIps' in value) || value['siteIps'] === undefined) return false;
    return true;
}

export function SiteFromJSON(json: any): Site {
    return SiteFromJSONTyped(json, false);
}

export function SiteFromJSONTyped(json: any, ignoreDiscriminator: boolean): Site {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'ipAddress': json['ip_address'] == null ? undefined : json['ip_address'],
        'timeZone': json['time_zone'] == null ? undefined : json['time_zone'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'siteIps': ((json['site_ips'] as Array<any>).map(SiteSiteIpsInnerFromJSON)),
    };
}

export function SiteToJSON(json: any): Site {
    return SiteToJSONTyped(json, false);
}

export function SiteToJSONTyped(value?: Site | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'ip_address': value['ipAddress'],
        'time_zone': value['timeZone'],
        'notes': value['notes'],
        'site_ips': ((value['siteIps'] as Array<any>).map(SiteSiteIpsInnerToJSON)),
    };
}

