/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow API
 * Access control and door management API for DoorFlow
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SiteSiteIpsInner
 */
export interface SiteSiteIpsInner {
    /**
     * IP address or CIDR range
     * @type {string}
     * @memberof SiteSiteIpsInner
     */
    ipAddress?: string;
}

/**
 * Check if a given object implements the SiteSiteIpsInner interface.
 */
export function instanceOfSiteSiteIpsInner(value: object): value is SiteSiteIpsInner {
    return true;
}

export function SiteSiteIpsInnerFromJSON(json: any): SiteSiteIpsInner {
    return SiteSiteIpsInnerFromJSONTyped(json, false);
}

export function SiteSiteIpsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteSiteIpsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'ipAddress': json['ip_address'] == null ? undefined : json['ip_address'],
    };
}

export function SiteSiteIpsInnerToJSON(json: any): SiteSiteIpsInner {
    return SiteSiteIpsInnerToJSONTyped(json, false);
}

export function SiteSiteIpsInnerToJSONTyped(value?: SiteSiteIpsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ip_address': value['ipAddress'],
    };
}

