/* tslint:disable */
/* eslint-disable */
/**
 * DoorFlow Public API
 * This is the DoorFlow Public API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@doorflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TriggerSync200Response
 */
export interface TriggerSync200Response {
    /**
     * 
     * @type {string}
     * @memberof TriggerSync200Response
     */
    result: string;
}

/**
 * Check if a given object implements the TriggerSync200Response interface.
 */
export function instanceOfTriggerSync200Response(value: object): value is TriggerSync200Response {
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function TriggerSync200ResponseFromJSON(json: any): TriggerSync200Response {
    return TriggerSync200ResponseFromJSONTyped(json, false);
}

export function TriggerSync200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriggerSync200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'],
    };
}

export function TriggerSync200ResponseToJSON(json: any): TriggerSync200Response {
    return TriggerSync200ResponseToJSONTyped(json, false);
}

export function TriggerSync200ResponseToJSONTyped(value?: TriggerSync200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'],
    };
}

